---
title: "GAMMs Whole Imputation Algorithm"
author: "CLETZ Laura"
date: "18/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(data.table)
library(dplyr)
library(tidyverse)
library(mgcv)
library(tibble)
library(tidyselect)
library(gam)
library(nlme)
here::i_am("Data_Imputations/GAMMS_imputation_algo.Rmd")
library(here)
```

```{r, warning=FALSE}
S1 <- read.table(here('processed','Source_S1.csv'), dec = '.', sep = ";", header = T) 
S1$Dates <- as.Date(S1$Dates, format="%Y-%m-%d")
S1$Corrected_Dates <- as.Date(S1$Corrected_Dates, format="%Y-%m-%d")
```

```{r, warning=FALSE}
COWG <- read.table(here('processed','COWG.csv'), dec = '.', sep = ";", header = T) 
COWG$Dates <- as.Date(COWG$Dates, format="%Y-%m-%d")
COWG$Corrected_Dates <- as.Date(COWG$Corrected_Dates, format="%Y-%m-%d")
```

```{r}
S1$Numeric_Dates <- as.numeric(S1$Corrected_Dates)
S1 <- S1 %>% relocate(Numeric_Dates, .before = Temperature)

COWG$Numeric_Dates <- as.numeric(COWG$Corrected_Dates)
COWG <- COWG %>% relocate(Numeric_Dates, .before = Temperature)
```

```{r}
safe_s1 <- S1[(1:86),]
safe_s1 <- safe_s1[which(colSums(is.na(safe_s1))*100/nrow(safe_s1)<=30)]
```

```{r}
safe_cowg <- COWG[(1:86),]
safe_cowg <- safe_cowg[which(colSums(is.na(safe_cowg))*100/nrow(safe_cowg)<=35)]
```

```{r}
factor_processing <- function(df){
  method_groups <- list()
  
    for (main_var in names(df)) {
    
      method_cols <- grep(paste0("^", main_var, "_[[:alnum:]]"), names(df), value = TRUE)
    
      if (length(method_cols) > 1 && main_var %in% names(df)) {
      
       method_label <- apply(df[, method_cols], 1, function(row) {
         if (sum(row, na.rm = TRUE) != 1) return(NA)
         return(gsub(paste0("^", main_var, "_"), "", method_cols[which(row == 1)]))
       })
        
       df[[paste0(main_var, "_method")]] <- factor(method_label)
      
       method_groups[[main_var]] <- method_cols
     }
  }

  # Remove the binary method indicators
    for (cols in method_groups) {
     df <- df[, !names(df) %in% cols]
    }
  
  return(df)
}
```

```{r}
safe_s1 <- factor_processing(safe_s1)
safe_cowg <- factor_processing(safe_cowg)
```


```{r}
step_GAMMs <- function(df) {
  
  list_final <- list()
  control <- lmeControl(msMaxIter = 200, msMaxEval = 200, tolerance = 1e-4,
                        niterEM = 50, opt = "optim")

  ## Stepwise GAMM fitting
  for (resp in 6:ncol(df)) { # Assuming first 4 columns are Dates, Rainfall, etc.
    
     if (is.factor(df[[resp]])) {
      cat("\nSkipping factor response variable:", names(df[resp]), "\n")
      next
     }
    
    cat('\nVariable:', names(df[resp]), '\n')
    
    best_bic <- Inf
    response_var <- names(df[resp])
    
    # Initial formula: random effects on all other variables
    formula <- paste0(response_var, ' ~ ')
    for (name in 3:ncol(df)) {
      if (name != resp) {
        formula <- paste0(formula, "s(", names(df)[name], ", bs='re') + ")
      }
    }
    formula <- formula(gsub('.{3}$', '', formula))
    cat('\nFormula:', as.character(formula), '\n')

    # Try initial model with ARMA correlation
    best_model <- try(gamm(formula, data = df, 
                   correlation = corARMA(form = ~1, p=1, q=1), 
                   family = gaussian(), control = control, na.action = na.omit),
                   silent = TRUE)
     if (inherits(best_model, "try-error")) {
        best_model <- try(gamm(formula, data = df, 
                     correlation = corARMA(form = ~1, p=1), 
                     family = gaussian(), control = control, na.action = na.omit),
                     silent = TRUE)
       if (inherits(best_model, "try-error")) {
          best_model <- try(gamm(formula, data = df, 
                       correlation = corARMA(form = ~1, q=1), 
                       family = gaussian(), control = control, na.action = na.omit),
                       silent = TRUE)
       }
     }

    current_bic <- BIC(best_model$lme)
    worst_pred <- list()

    while (current_bic <= best_bic) {
      
      fit <- summary(best_model$gam)
      fit <- rownames_to_column(data.frame(fit$s.table), var = "term")
      fit$term <- gsub("^.{2}|.{1}$", "", fit$term)

      minus_pred <- fit$term[which.max(fit$p.value)]
      worst_pred <- append(worst_pred, minus_pred)

      
      formula <- paste0(response_var, ' ~ ')
      for (name in 3:ncol(df)) {
        
        var_name <- names(df)[name]
        
        if (name != resp && !(var_name %in% worst_pred)) {
          formula <- paste0(formula, "s(", var_name, ", bs='re') + ")
        }
      }
      
      formula <- formula(gsub('.{3}$', '', formula))
      cat('\nNew formula:', as.character(formula), '\n')
      
      if (length(worst_pred) > (ncol(df) - 5)) {
        cat('\nThis formula is too small! \n')
        break
      }

      model <- try(gamm(formula, data = df, 
                   correlation = corARMA(form = ~1, p=1, q=1), 
                   family = gaussian(), control = control, na.action = na.omit),
                   silent = TRUE)
     if (inherits(model, "try-error")) {
        model <- try(gamm(formula, data = df, 
                     correlation = corARMA(form = ~1, p=1), 
                     family = gaussian(), control = control, na.action = na.omit),
                     silent = TRUE)
       if (inherits(model, "try-error")) {
          model <- try(gamm(formula, data = df, 
                       correlation = corARMA(form = ~1, q=1), 
                       family = gaussian(), control = control, na.action = na.omit),
                       silent = TRUE)
       }
     }

      current_bic <- BIC(model$lme)
      
      if (current_bic < best_bic) {
        best_bic <- current_bic
        best_model <- model
        current_bic <- current_bic - 1 
        cat('\nA better model has been chosen! \n')
      }
    }

    list_model <- list(response_var, best_model)
    list_final <- c(list_final, list(list_model))
  }

  return(list_final)
}
```

```{r}
safe_s1 <- safe_s1[c(1:9, 11, 14, 16, 18, 20, 22, 24:27, 29:30, 32, 35)]
gam_res <- step_GAMMs(safe_s1)
```

```{r}
safe_cowg <- safe_cowg[c(1:9, 11, 14, 16, 18, 20, 22, 24:27, 29:30, 32, 35)]
gam_res2 <- step_GAMMs(safe_cowg)
```

```{r}
impute_GAMMs <- function(df, model){
  
  list_final <- list()
  method_index <- grep("method", names(df))
  
  for(resp in 6:ncol(df[-method_index])){  # Skip Dates, Rainfall, and method cols
    list_na <- list()
    list_resp <- list()
    
    index_with_na <- which(is.na(df[[resp]]))
    
    if(length(index_with_na) == 0) next
    
    cat("\nImputation of variable", names(df)[resp])
    
    newdf <- df[index_with_na, , drop = FALSE]
    
    
    for(col in names(newdf)){
      if(is.numeric(newdf[[col]])){
        newdf[[col]][is.na(newdf[[col]])] <- mean(df[[col]], na.rm = TRUE)
      }
    }
    
    
    method_cols <- grep("_method$", names(newdf), value = TRUE)
    for(mc in method_cols){
      newdf[[mc]] <- factor(newdf[[mc]], levels = levels(df[[mc]]))
      
      if(any(is.na(newdf[[mc]]))){
        levels(newdf[[mc]]) <- c(levels(newdf[[mc]]), "missing")
        newdf[[mc]][is.na(newdf[[mc]])] <- "missing"
      }
    }
    
    list_na <- append(list_na, list(index_with_na))
    list_resp <- append(list_resp, names(df)[resp])
    list_final <- append(list_final, list(list_resp, list_na))
    
    
    index <- 1
    while(names(df)[resp] != model[[index]][[1]]){
      index <- index + 1
      if(index > length(model)) stop("Model for response variable not found")
    }
    
    formula <- model[[index]][[2]]$gam$formula
    cat(' using formula:', as.character(formula), '\n')
    
    gamm <- model[[index]][[2]]$gam
    
    # Predict the NAs
    df[[resp]][index_with_na] <- predict.gam(gamm, newdf, na.action = na.exclude)
  }
  return(list(df, list_final))
}

```

```{r}
res_impute <- impute_GAMMs(safe_s1, gam_res)
res_impute2 <- impute_GAMMs(safe_cowg, gam_res2)
```

```{r}
impute_iter <- function(imputed, model, max_iter = 10, tol = 1e-4) {

  df <- imputed[[1]]
  df_old <- df
  method_index <- grep("method", names(df))

  
  for (iter in 1:max_iter) {
    cat("\nIteration", iter, "\n")

    for (resp in 6:ncol(df[-method_index])) {

      names_index <- 1
      while (names(df[resp]) != imputed[[2]][[names_index]]) {
        names_index <- names_index + 1
      }
      
      index_with_na <- unlist(imputed[[2]][[names_index + 1]])

      newdf <- df[index_with_na, , drop = FALSE]
      
      for (col in names(newdf)) {
        if (is.numeric(newdf[[col]])) {
          newdf[[col]][is.na(newdf[[col]])] <- mean(df[[col]], na.rm = TRUE)
        }
      }
      
      method_cols <- grep("_method$", names(newdf), value = TRUE)
      for (mc in method_cols) {
        newdf[[mc]] <- factor(newdf[[mc]], levels = levels(df[[mc]]))
        
        if(any(is.na(newdf[[mc]]))) {
          levels(newdf[[mc]]) <- c(levels(newdf[[mc]]), "missing")
          newdf[[mc]][is.na(newdf[[mc]])] <- "missing"
        }
      }
      
      gam_index <- 1
      while (names(df[resp]) != model[[gam_index]][[1]]) {
        gam_index <- gam_index + 1
      }
      gamm <- model[[gam_index]][[2]]$gam

      df[[resp]][index_with_na] <- predict.gam(gamm, newdf, na.action = na.exclude)
    }
    
    threshold <- sum(( df_old[-c(1:2, method_index)] - df[-c(1:2, method_index)] )^2, na.rm = TRUE)
    cat("\nPrecision reached:", threshold, "but tolerance's threshold is:", tol, "\n")
    
    if ( threshold < tol) {
      cat("\nConverged at iteration", iter, "\n")
      break
    }
    
    df_old <- df
  }

  return(df)
}
```

```{r}
S1_complete <- impute_iter(res_impute, gam_res, max_iter = 200)
COWG_complete <- impute_iter(res_impute2, gam_res2, max_iter = 200)
```

```{r}
write_delim(S1_complete, here("processed", "S1_gamm_2004_2011.csv"), delim=";")
write_delim(COWG_complete, here("processed", "COWG_gamm_2004_2011.csv"), delim=";")
```

```{r}
impute_byrow <- function(na_df, df, model){
  
  index <- nrow(df)
  list_final <- list()
  
  while( index < nrow(na_df) ){
    
    cat("\n Il reste", nrow(na_df)-nrow(df), "ligne(s) à compléter")
    
    last_date <- df[[1]][nrow(df)]
    corres_index <- which(na_df[[1]] == as.Date(last_date))
    
    if(index + 2 > nrow(na_df)){
      
      cat("\n Traitement de la ligne après la date", as.character(last_date))
    
      next_rows <- na_df[ corres_index + 1, ]
    
      df <- df %>% bind_rows(next_rows)
      l <- impute_GAMMs(df, model)
      
      df <- l[[1]]
      list_ind <- l[[2]]
      list_final <- append(list_final, list_ind)
    
      cat("\n Imputation de la nouvelle ligne réussie")
    
      index <- index + 1
      
    } else { 
      cat("\n Traitement des deux lignes après la date", as.character(last_date))
    
      next_rows <- na_df[ c(corres_index + 1, corres_index + 2), ]
    
      df <- df %>% bind_rows(next_rows)
      l <- impute_GAMMs(df, model)
      
      df <- l[[1]]
      list_ind <- l[[2]]
      list_final <- append(list_final, list_ind)
    
      cat("\n Imputation des nouvelles lignes réussie")
      
      index <- index + 2 }
  }
  
  return(list(df, list_final))
}
```

```{r}
S1 <- S1 %>% factor_processing() %>% select( names(safe_s1) )
COWG <- COWG %>% factor_processing() %>% select( names(safe_cowg) )
```

```{r}
S1_complete_long <- impute_byrow(S1, S1_complete, gam_res)
COWG_complete_long <- impute_byrow(COWG, COWG_complete, gam_res2)
```

```{r}
list_var <- list()
list_na <- list()
list_final <- list()

n <- length(S1_complete_long[[2]])

for (col in 6:ncol(S1)) {
  var <- list()

  for (i in 1:n) {
    if (names(S1[col]) == S1_complete_long[[2]][[i]]) {
      var <- c(var, S1_complete_long[[2]][[i + 1]])
    }
  }

  var <- unlist(var)
  list_na <- append(list_na, list(var))
  list_var <- append(list_var, list(names(S1[col])))
  list_final <- append(list_final, list(list_var, list_na))
}

list_final <- c( list_final[[35]][1:12], list_final[[36]][1:12] )

new_order <- as.vector(rbind(1:12, 13:24))
reordered_list <- list_final[new_order]

new_impute <- list(S1_complete_long[[1]], reordered_list)

new_impute[[2]] <- lapply( seq_along(new_impute[[2]]), function(i) list( new_impute[[2]][[i]] ) )

attempt <- impute_iter(new_impute, gam_res, max_iter = 1000)
```

```{r}
write_delim(attempt, here('processed', 'S1_gamm_2004_2018.csv'), delim=";")
```


```{r}
list_var <- list()
list_na <- list()
list_final <- list()

n <- length(COWG_complete_long[[2]])

for (col in 6:ncol(COWG)) {
  var <- list()

  for (i in 1:n) {
    if (names(COWG[col]) == COWG_complete_long[[2]][[i]]) {
      var <- c(var, COWG_complete_long[[2]][[i + 1]])
    }
  }

  var <- unlist(var)
  list_na <- append(list_na, list(var))
  list_var <- append(list_var, list(names(COWG[col])))
  list_final <- append(list_final, list(list_var, list_na))
}

list_final <- c( list_final[[35]][1:12], list_final[[36]][1:12] )

new_order <- as.vector(rbind(1:12, 13:24))
reordered_list <- list_final[new_order]

new_impute <- list(COWG_complete_long[[1]], reordered_list)

new_impute[[2]] <- lapply( seq_along(new_impute[[2]]), function(i) list( new_impute[[2]][[i]] ) )

attempt <- impute_iter(new_impute, gam_res2, max_iter = 1000)
```

```{r}
write_delim(attempt, here('processed', 'COWG_gamm_2004_2018.csv'), delim=";")
```







