---
title: "Descriptive Statistics on Amous +1200 with Generargues weather"
author: "CLETZ Laura"
date: "12/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(data.table)
library(dplyr)
library(tidyverse)
library(lubridate)
here::i_am("R/Amous1200_desc_stat.Rmd")
library(here)
```

# Amous+1200 MD imputation

```{r, warning=FALSE}
amous <- read.table(here('processed','Amous_1200.csv'), sep=';', dec='.', header=T) 
data$dates <- as.Date(data$dates, format = "%Y-%m-%d")
data$corrected_dates <- as.Date(data$corrected_dates, format = "%Y-%m-%d")
```

# Rainfall time series 

```{r}
rain <- ts(data$rainfall, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(rain, xlab='Time', ylab="Precipitations (in mm)")
# mm = L/m^2
```

```{r, echo=FALSE}
fit_rain <- decompose(rain)
plot(fit_rain)
```

```{r}
monthplot(rain, ylab = "Precipitations (in mm)")
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(rain, type="correlation", main='')
acf(rain, type="partial", main='')
```

# Rainfall after a 30-days delay time series

```{r}
rain2 <- ts(data$rainfall_lag_1, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(rain2, xlab='Time')
```

```{r}
fit_rain2 <- decompose(rain2)
plot(fit_rain2)
```

```{r}
monthplot(rain2)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(rain2, type="correlation", main='')
acf(rain2, type="partial", main='')
```

# Temperature time series 

```{r}
temp <- ts(data$temperature, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(temp, xlab='Time')
```

```{r, echo=FALSE}
fit_temp <- decompose(temp)
plot(fit_temp)
```

```{r}
monthplot(temp)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(temp, type="correlation", main='')
acf(temp, type="partial", main='')
```

# pH time series 

```{r}
ph <- ts(data$ph, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(ph, xlab='Time')
```

```{r, echo=FALSE}
fit_ph <- decompose(ph)
plot(fit_ph)
```

```{r}
monthplot(ph)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(ph, type="correlation", main='')
acf(ph, type="partial", main='')
```

# O2 time series 

```{r}
o2 <- ts(data$o2, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(o2, xlab='Time')
```

```{r, echo=FALSE}
fit_o2 <- decompose(o2)
plot(fit_o2)
```

```{r}
monthplot(o2)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(o2, type="correlation", main='')
acf(o2, type="partial", main='')
```

# Conductivity time series 

```{r}
cond <- ts(data$conductivity, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(cond, xlab='Time')
```

```{r, echo=FALSE}
fit_cond <- decompose(cond)
plot(fit_cond)
```

```{r}
monthplot(cond)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(cond, type="correlation", main='')
acf(cond, type="partial", main='')
```

# Lead time series 

```{r}
lead <- ts(data$lead, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(lead, xlab='Time')
```

```{r, echo=FALSE}
fit_lead <- decompose(lead)
plot(fit_lead)
```

```{r}
monthplot(lead)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(lead, type="correlation", main='')
acf(lead, type="partial", main='')
```

# Antimony time series 

```{r}
antimony <- ts(data$antimony, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(antimony, xlab='Time')
```

```{r, echo=FALSE}
fit_antimony <- decompose(antimony)
plot(fit_antimony)
```

```{r}
monthplot(antimony)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(antimony, type="correlation", main='')
acf(antimony, type="partial", main='')
```

# Total Arsenic time series 

```{r}
arsenic <- ts(data$total_arsenic, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(arsenic, xlab='Time')
```

```{r, echo=FALSE}
fit_arsenic <- decompose(arsenic)
plot(fit_arsenic)
```

```{r}
monthplot(arsenic)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(arsenic, type="correlation", main='')
acf(arsenic, type="partial", main='')
```

# Sulfate time series 

```{r}
sulfate <- ts(data$sulfate, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(sulfate, xlab='Time')
```

```{r, echo=FALSE}
fit_sulfate <- decompose(sulfate)
plot(fit_sulfate)
```

```{r}
monthplot(sulfate)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(sulfate, type="correlation", main='')
acf(sulfate, type="partial", main='')
```

# Zinc time series 

```{r}
zinc <- ts(data$zinc, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(zinc, xlab='Time')
```

```{r, echo=FALSE}
fit_zinc <- decompose(zinc)
plot(fit_zinc)
```

```{r}
monthplot(zinc)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(zinc, type="correlation", main='')
acf(zinc, type="partial", main='')
```

# Cadmium time series 

```{r}
cadmium <- ts(data$cadmium, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(cadmium, xlab='Time')
```

```{r, echo=FALSE}
fit_cadmium <- decompose(cadmium)
plot(fit_cadmium)
```

```{r}
monthplot(cadmium)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(cadmium, type="correlation", main='')
acf(cadmium, type="partial", main='')
```

# Copper time series 

```{r}
copper <- ts(data$copper, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(copper, xlab='Time')
```

```{r, echo=FALSE}
fit_copper <- decompose(copper)
plot(fit_copper)
```

```{r}
monthplot(copper)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(copper, type="correlation", main='')
acf(copper, type="partial", main='')
```

# Ferrous Ion time series 

```{r}
ion <- ts(data$feII, start = c(2004,10), end = c(2019,3), frequency = 12)
plot.ts(ion, xlab='Time')
```

```{r, echo=FALSE}
fit_ion <- decompose(ion)
plot(fit_ion)
```

```{r}
monthplot(ion)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
acf(ion, type="correlation", main='')
acf(ion, type="partial", main='')
```

# General study

```{r}
fit <- data.frame(
  Dates = data$corrected_dates,
  Sb = as.numeric(fit_antimony$trend),
  As = as.numeric(fit_arsenic$trend),
  Cd = as.numeric(fit_cadmium$trend),
  conductivity = as.numeric(fit_cond$trend),
  Cu = as.numeric(fit_copper$trend),
  FeII = as.numeric(fit_ion$trend),
  Pb = as.numeric(fit_lead$trend),
  o2 = as.numeric(fit_o2$trend),
  ph = as.numeric(fit_ph$trend), 
  Pluie = as.numeric(fit_rain$trend),
  Pluie_30daysdelay = as.numeric(fit_rain2$trend),
  SO4_2 = as.numeric(fit_sulfate$trend),
  temperature = as.numeric(fit_temp$trend),
  Zn = as.numeric(fit_zinc$trend)
)
```

```{r, warning=FALSE}
library(ggplot2)
library(scales)

fit_scaled <- fit %>%
  mutate_at(names(fit[2:15]),
            function(x) rescale(x))
```

```{r}
last_points <- fit_scaled %>%
  summarise(
    Dates = Dates[168] + 90,
    Sb = Sb[168],
    As = As[168],
    Cd = Cd[168],
    Conductivité = conductivity[168],
    Cu = Cu[168],
    FeII = FeII[168],
    O2 = o2[168],
    pH = ph[168],
    Pluie = Pluie[168],
    Pluie_30_jours_avant = Pluie_30daysdelay[168],
    Pb = Pb[168],
    SO4_2 = SO4_2[168],
    Température = temperature[168],
    Zn = Zn[168]
  ) %>%
  tidyr::pivot_longer(
    -Dates,
    names_to = "Variable",
    values_to = "Value"
  )
```

```{r}
library(plotly)

p <- ggplot(fit_scaled, aes(x = Dates)) + 
  geom_line(aes(y = Sb, color = "Sb")) + 
  geom_line(aes(y = As, color = "As")) + 
  geom_line(aes(y = Cd, color = "Cd")) + 
  geom_line(aes(y = conductivity, color = "Conductivité")) + 
  geom_line(aes(y = Cu, color = "Cu")) + 
  geom_line(aes(y = FeII, color = "FeII")) + 
  geom_line(aes(y = o2, color = "O2")) + 
  geom_line(aes(y = ph, color = "pH")) + 
  geom_line(aes(y = Pluie, color = "Pluie des 30 derniers jours")) + 
  geom_line(aes(y = Pluie_30daysdelay, color = "Pluie des 30 jours encore avant")) +
  geom_line(aes(y = Pb, color = "Pb")) +
  geom_line(aes(y = SO4_2, color = "SO4 2-")) + 
  geom_line(aes(y = temperature, color = "Température")) + 
  geom_line(aes(y = Zn, color = "Zn")) + 
  scale_x_date(breaks = data$corrected_dates, date_breaks = "9 months", labels = date_format("%Y-%m")) +
  labs(y = "Valeurs standardisées", color = "Variables") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15)) +
  geom_text(
    data = last_points,
    aes(x = Dates, y = Value, label = Variable, color = Variable),
    inherit.aes = FALSE,
   # hjust = -10,
    vjust = 0.5,
    show.legend = FALSE
  )

g <- ggplotly(p) %>% 
  layout(hovermode = "x unified")
g
```

```{r}
library(htmlwidgets)
saveWidget(g, here("Meetings","Amous1200_gamm_interactive_plot.html"), selfcontained = TRUE)
```

