---
title: "FAMD with COWG's data"
author: "CLETZ Laura"
date: "03/07/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(mgcv)
library(rlang)
library(ggplot2)
library(Hmisc)
library(GGally)
library(dplyr)
library(FactoMineR)
library(factoextra)
here::i_am("Correlations_and_Predictions/FAMD_COWG.Rmd")
library(here)
```

```{r}
levels(data_diff$O2_method) <- c(levels(data_diff$O2_method), "Undetermined_O2_method")
data_diff$O2_method[ is.na( data_diff$O2_method ) ] <- "Undetermined_O2_method"

levels(data_diff$Cadmium_method) <- c(levels(data_diff$Cadmium_method), "Undetermined_Cadmium_method")
data_diff$Cadmium_method[ is.na( data_diff$Cadmium_method ) ] <- "Undetermined_Cadmium_method"

levels(data_diff$Antimoine_method) <- c(levels(data_diff$Antimoine_method), "Undetermined_Antimoine_method")
data_diff$Antimoine_method[ is.na( data_diff$Antimoine_method ) ] <- "Undetermined_Antimoine_method"

levels(data_diff$Cuivre_method) <- c(levels(data_diff$Cuivre_method), "Undetermined_Cuivre_method")
data_diff$Cuivre_method[ is.na( data_diff$Cuivre_method ) ] <- "Undetermined_Cuivre_method"

levels(data_diff$Plomb_method) <- c(levels(data_diff$Plomb_method), "Undetermined_Plomb_method")
data_diff$Plomb_method[ is.na( data_diff$Plomb_method ) ] <- "Undetermined_Plomb_method"

levels(data_diff$Zinc_method) <- c(levels(data_diff$Zinc_method), "Undetermined_Zinc_method")
data_diff$Zinc_method[ is.na( data_diff$Zinc_method ) ] <- "Undetermined_Zinc_method"
```

```{r}
Period <- c( rep("2009-2012", 8), rep("2012-2015", 43-8), rep("2015-2019", 88-43), rep("2019-2022", 127-88) )
data_diff <- data_diff %>% bind_cols(Period)
colnames(data_diff)[24] <- "Period"
data_diff$Period <- as.factor(data_diff$Period)
```

```{r}
res.famd <- FAMD(data_diff[,3:24], graph = FALSE, ncp = Inf)
res.famd$eig
```
```{r}
var_names <- rownames(res.famd$var$coord)
custom_groups <- ifelse(var_names %in% var_names[c(1:7, 22)],
                        "Éléments physico-chimiques et temps",
                        ifelse(var_names %in% var_names[8:15],
                        "Éléments traces (métalloïdes)",
                        "Méthodes de mesure"))

fviz_famd_var(res.famd, 
             axes = c(1,2), 
             repel = TRUE, 
             col.var = custom_groups,  
             palette = c("blue", "red", "darkgreen"),
             ggtheme = theme_minimal(),
             title = "FAMD Variables Plot")

fviz_famd_ind(res.famd,
             axes = c(1, 2),
             repel = TRUE,
             ggtheme = theme_minimal(),
             col.ind = "cos2",
             label = "quali.var",
             title = "FAMD Individuals Plot")
```

```{r}
res.famd <- FAMD(data_diff[,3:24], graph = FALSE, sup.var = c(17:23))
res.famd$eig
```

```{r}
var_names <- rownames(res.famd$var$coord)
custom_groups <- ifelse(var_names %in% var_names[c(1:7, 22)],
                        "Éléments physico-chimiques et temps",
                        "Éléments traces (métalloïdes)")

fviz_famd_var(res.famd, 
             axes = c(1, 2), 
             repel = TRUE, 
             col.var = custom_groups,  
             palette = c("blue", "red"),
             col.var.sup = "darkgreen",
             ggtheme = theme_minimal(),
             title = "FAMD Variables Plot")

fviz_famd_ind(res.famd,
             axes = c(1, 2),
             repel = TRUE,
             ggtheme = theme_minimal(),
             col.ind = "cos2",
             label = "none",
             title = "FAMD Individuals Plot")
```

```{r}
fviz_famd_var(res.famd, 
             axes = c(1,3), 
             repel = TRUE, 
             col.var = custom_groups,  
             palette = c("blue", "red"),
             col.var.sup = "darkgreen",
             ggtheme = theme_minimal(),
             title = "FAMD Variables Plot")

fviz_famd_ind(res.famd,
             axes = c(1,3),
             repel = TRUE,
             ggtheme = theme_minimal(),
             col.ind = "cos2",
             label = "none",
             title = "FAMD Individuals Plot")
```

```{r}
dimdesc(res.famd)
```

```{r}
test <- read.table(here("processed","COWG.csv"), sep=";", dec=".", header=T)

test <- test[which(colSums(is.na(test[(1:86),]))*100/nrow(test[(1:86),])<=35)] %>%
  mutate_at(1:2, function(x) as.Date(x, format="%Y-%m-%d")) %>%
  factor_processing() %>%
  select(names(data_diff[,-c(5,24)]))
```

```{r}
na_index <- unique(unlist(
  lapply(test[, 5:16], function(col) which(is.na(col)))
))
```

```{r}
#res.famd <- FAMD(data_diff[,3:24], graph = FALSE, sup.var = c(17:23), ind.sup = na_index)
#res.famd$eig
#It seems that we can't run a FAMD with 152 supplementary rows...
```

```{r}
var_names <- rownames(res.famd$var$coord)
custom_groups <- ifelse(var_names %in% var_names[c(1:7, 22)],
                        "Éléments physico-chimiques et temps",
                        "Éléments traces (métalloïdes)")

fviz_famd_var(res.famd, 
             axes = c(1,2), 
             repel = TRUE, 
             col.var = custom_groups,  
             palette = c("blue", "red"),
             col.var.sup = "darkgreen",
             ggtheme = theme_minimal(),
             title = "FAMD Variables Plot")

fviz_famd_ind(res.famd,
             axes = c(1, 2),
             repel = TRUE,
             ggtheme = theme_minimal(),
             col.ind = "cos2",
             label = "none",
             title = "FAMD Individuals Plot")
```

```{r}
cd <- catdes(data_diff[,3:24], 18)
plot.catdes(cd)
```
