---
title: "Variance comparison with COWG's data"
author: "CLETZ Laura"
date: "03/07/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(mgcv)
library(rlang)
library(ggplot2)
library(Hmisc)
library(GGally)
library(dplyr)
library(FactoMineR)
library(factoextra)
library(car)
here::i_am("Correlations_and_Predictions/var_comparison_COWG.Rmd")
library(here)
```

```{r}
data_small <- read.table(here("processed", "COWG_gamm_2004_2011.csv"), sep=";", dec=".", header=T) %>% 
  mutate_at(18:23, as.factor)
data_small$Dates <- as.Date(data_small$Dates, format = "%Y-%m-%d")
data_small$Corrected_Dates <- as.Date(data_small$Corrected_Dates, format = "%Y-%m-%d")
```

```{r}
data_big <- read.table(here("processed", "COWG_gamm_2004_2018.csv"), sep=";", dec=".", header=T) %>% 
  mutate_at(18:23, as.factor)
data_big$Dates <- as.Date(data_big$Dates, format = "%Y-%m-%d")
data_big$Corrected_Dates <- as.Date(data_big$Corrected_Dates, format = "%Y-%m-%d")
```

```{r}
leveneTest(data_small$Rainfall, group = data_small$O2_method, data = data_small)
leveneTest(data_small$Conductivité, group = data_small$Plomb_method, data = data_small)
leveneTest(data_big$Rainfall, group = data_big$O2_method, data = data_big)
leveneTest(data_big$Conductivité, group = data_big$Plomb_method, data = data_big)
```

Variances are not homogenous.

```{r}
data_diff <- data_big %>%
  anti_join(data_small, by = "Corrected_Dates")

sd(data_big$Arsenic_Total)
sd(data_diff$Arsenic_Total)
sd(data_small$Arsenic_Total)
```

By periods (depending on number of imputations):
```{r}
Period <- c( rep("2004-2009", 47), rep("2009-2012", 87-47), rep("2012-2019", 174-87), rep("2019-2022", 213-174))
data_big <- data_big %>% bind_cols(Period)
colnames(data_big)[24] <- "Period"
data_big$Period <- as.factor(data_big$Period)
```

```{r}
var.test(data_small$Temperature, data_diff$Temperature)
var.test(data_small$Antimoine, data_diff$Antimoine)
var.test(data_small$O2, data_diff$O2)
var.test(data_small$Arsenic_Total, data_diff$Arsenic_Total)
```

Variances between 2004-2009 and 2009-2022 are different.

```{r, warning=FALSE}
ggplot(data_big, aes(x = Period, y = Arsenic_Total, colour = Period)) +
  geom_violin() + 
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  theme_minimal() +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```

```{r, warning=FALSE}
ggplot(data_big, aes(x = Period, y = Rainfall_lag_1, colour = Period)) +
  geom_violin() + 
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  theme_minimal() +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```

```{r, warning=FALSE}
ggplot(data_big, aes(x = Period, y = O2, colour = O2_method)) +
  geom_violin() + 
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  theme_minimal() +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```

```{r, warning=FALSE}
ggplot(data_big, aes(x = Period, y = Cuivre, colour = Cuivre_method)) +
  geom_violin() + 
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  theme_minimal() +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```
