---
title: "Character to Numeric Processing"
author: "CLETZ Laura"
date: "26/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
here::i_am("Data_Processing/chr_to_num_processing.Rmd")
library(here)
```

```{r}
S1 <- read.table(here("processed","Source_S1.csv"), dec=c(".",","), sep=";", header=T)
S1$Dates <- as.Date(S1$Dates, format = "%Y-%m-%d")
```

```{r}
S5 <- read.table(here("processed","S5.csv"), dec=c(".",","), sep=";", header=T)
S5$Dates <- as.Date(S5$Dates, format = "%Y-%m-%d")
```

```{r}
COWG <- read.table(here("processed","COWG.csv"), dec=c(".",","), sep=";", header=T)
COWG$Dates <- as.Date(COWG$Dates, format = "%Y-%m-%d")
```

```{r}
GAL <- read.table(here("processed","GAL.csv"), dec=c(".",","), sep=";", header=T)
GAL$Dates <- as.Date(GAL$Dates, format = "%Y-%m-%d")
```

```{r}
Confluence <- read.table(here("processed","Confluence.csv"), dec=c(".",","), sep=";", header=T)
Confluence$Dates <- as.Date(Confluence$Dates, format = "%Y-%m-%d")
```

```{r}
Amous <- read.table(here("processed","Amous_1200.csv"), dec=c(".",","), sep=";", header=T)
Amous$Dates <- as.Date(Amous$Dates, format = "%Y-%m-%d")
```

```{r}
factor_processing <- function(df){
  method_groups <- list()
  
    for (main_var in names(df)) {
    
      method_cols <- grep(paste0("^", main_var, "_[[:alnum:]]"), names(df), value = TRUE)
    
      if (length(method_cols) > 1 && main_var %in% names(df)) {
      
       method_label <- apply(df[, method_cols], 1, function(row) {
         if (sum(row, na.rm = TRUE) != 1) return(NA)
         return(gsub(paste0("^", main_var, "_"), "", method_cols[which(row == 1)]))
       })
        
       df[[paste0(main_var, "_method")]] <- factor(method_label)
      
       method_groups[[main_var]] <- method_cols
     }
  }

  # Remove the binary method indicators
    for (cols in method_groups) {
     df <- df[, !names(df) %in% cols]
    }
  
  return(df)
}
```

```{r}
S1 <- factor_processing(S1)
S5 <- factor_processing(S5)
COWG <- factor_processing(COWG)
GAL <- factor_processing(GAL)
Confluence <- factor_processing(Confluence)
Amous <- factor_processing(Amous)
```

```{r}
LOD <- read.table(here("processed","LOD_table.csv"), dec=".", sep=";", header=T)
```

```{r}
chr_to_num <- function(df) {
  
  index <- grep("<1", df$O2)
  df$O2[index] <- "0,5"

  index <- grep("≥9|≥8", df$O2)
  df$O2[index] <- "9"

  index <- grep("≥200000", df$Conductivité)
  df$Conductivité[index] <- "200000"

  for (name in names(LOD)) {
    if (name %in% names(df)) {
      index <- grep("<LD|<LQ|<LOD|< LD|< LQ|< LOD", df[[name]])
      if (length(index) > 0) {
        replacement <- gsub("\\.", ",", as.character(LOD[[name]][1]))
        df[[name]][index] <- replacement
      }
    }
  }

  for (name in names(df)) {
    if (inherits(df[[name]], "Date") || is.factor(df[[name]])) {
      next
    } else {
      df[[name]] <- gsub(",", ".", df[[name]])
      df[[name]] <- suppressWarnings(as.numeric(df[[name]]))
    }
  }

  return(df)
}
```

```{r}
S1 <- chr_to_num(S1)
S5 <- chr_to_num(S5)
COWG <- chr_to_num(COWG)
GAL <- chr_to_num(GAL)
Confluence <- chr_to_num(Confluence)
Amous <- chr_to_num(Amous)
```

```{r}
write_delim(S1, here("processed","Source_S1.csv"), delim=";")
write_delim(S5, here("processed","S5.csv"), delim=";")
write_delim(COWG, here("processed","COWG.csv"), delim=";")
write_delim(GAL, here("processed","GAL.csv"), delim=";")
write_delim(Confluence, here("processed","Confluence.csv"), delim=";")
write_delim(Amous, here("processed","Amous_1200.csv"), delim=";")
```
