---
title: "COWG recent datas processing"
author: "CLETZ Laura"
date: "11/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(dplyr)
library(tidyverse)
here::i_am("Data_Processing/tidy_datas.Rmd")
library(here)
```

```{r}
cowg <- read.table(here("raw_data","Carnoules_compas 2019_2021-vérifié-2.csv"), 
                   dec=c(",","."), sep=";", na.strings = c("NA", ""))[-c(1,106:111),]
rownames(cowg) <- 1:nrow(cowg)
```


Cleaning dates format:
```{r}
dates <- cowg[1,3:101]

parse_date_time_robust <- function(x){
   parse_date_time(
     x,
     orders = c('dmy','dmY','mdy','mdY','ymd','y-md'),
     quiet=TRUE
   )
}
dates <- parse_date_time_robust(dates)
```

```{r}
COWG <- data.frame(
  "Dates" = dates,
  "Temperature" = as.numeric(cowg[2,3:101]),
  "pH" = as.numeric(gsub(",", ".", cowg[3,3:101])),
  "Eh" = as.numeric(gsub(",", ".", cowg[4,3:101])),
  "Conductivité" = as.numeric(gsub(",", ".", cowg[5,3:101])),
  "O2" = as.numeric(gsub(",", ".", cowg[10,3:101])),
  "O2_HACH" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[10,3:101]))), 0,1),
  "O2_Colorimétrie" = rep(0, 101-2),
  "O2_Mettler" = rep(0, 101-2),
  "Aluminium" = as.numeric(gsub(",", ".", cowg[34,3:101])),
  "Antimoine" = as.numeric(gsub(",", ".", cowg[66,3:101])),
  "Antimoine_123Sb" = rep(0, 101-2),
  "Antimoine_121Sb" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[66,3:101]))), 0,1),
  "Arséniate" = as.numeric(gsub(",", ".", cowg[23,3:101])),
  "Arsénite" = as.numeric(gsub(",", ".", cowg[24,3:101])),
  "Arsenic_Total" = as.numeric(cowg[25,3:101]),
  "Baryum" = as.numeric(gsub(",", ".", cowg[70,3:101])),
  "Baryum_138Ba" = rep(0, 101-2),
  "Baryum_137Ba" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[70,3:101]))), 0,1),
  "Baryum_136Ba" = rep(0, 101-2),
  "Bore" = as.numeric(gsub(",", ".", cowg[31,3:101])),
  "Cadmium" = as.numeric(gsub(",", ".", cowg[62,3:101])),
  "Cadmium_114Cd" = rep(0, 101-2),
  "Cadmium_111Cd" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[62,3:101]))), 0,1),
  "Calcium" = as.numeric(gsub(",", ".", cowg[37,3:101])),
  "Calcium_44Ca" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[37,3:101]))), 0,1),
  "Calcium_43Ca" = rep(0, 101-2),
  "Césium" = as.numeric(gsub(",", ".", cowg[68,3:101])),
  "Chrome" = as.numeric(gsub(",", ".", cowg[41,3:101])),
  "Chrome_53Cr" = rep(0, 101-2),
  "Chrome_52Cr" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[41,3:101]))), 0,1),
  "Cobalt" = as.numeric(gsub(",", ".", cowg[45,3:101])),
  "Cuivre" = as.numeric(gsub(",", ".", cowg[48,3:101])),
  "Cuivre_65Cu" = rep(0, 101-2),
  "Cuivre_63Cu" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[48,3:101]))), 0,1),
  "Fer_Total" = as.numeric(gsub(",", ".", cowg[44,3:101])),
  "Lanthane" = as.numeric(gsub(",", ".", cowg[72,3:101])),
  "Magnésium" = as.numeric(gsub(",", ".", cowg[33,3:101])),
  "Nickel" = as.numeric(gsub(",", ".", cowg[46,3:101])),
  "Nickel_62Ni" = rep(0, 101-2),
  "Nickel_60Ni" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[46,3:101]))), 0,1),
  "Plomb" = as.numeric(gsub(",", ".", cowg[77,3:101])),
  "Plomb_208Pb" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[77,3:101]))), 0,1),
  "Plomb_207Pb" = rep(0, 101-2),
  "Plomb_206Pb" = rep(0, 101-2),
  "Rubidium" = as.numeric(gsub(",", ".", cowg[55,3:101])),
  "Sodium" = as.numeric(gsub(",", ".", cowg[32,3:101])),
  "Souffre" = as.numeric(gsub(",", ".", cowg[35,3:101])),
  "Strontium" = as.numeric(gsub(",", ".", cowg[57,3:101])),
  "Strontium_88Sr" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[57,3:101]))), 0,1),
  "Strontium_86Sr" = rep(0, 101-2),
  "Thallium" = as.numeric(gsub(",", ".", cowg[74,3:101])),
  "Thallium_205Tl" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[74,3:101]))), 0,1),
  "Thallium_203Tl" = rep(0, 101-2),
  "Titane" = as.numeric(gsub(",", ".", cowg[38,3:101])),
  "Titane_49Ti" = rep(0, 101-2),
  "Titane_47Ti" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[38,3:101]))), 0,1),
  "Vanadium" = as.numeric(gsub(",", ".", cowg[40,3:101])),
  "Yttrium" = as.numeric(gsub(",", ".", cowg[58,3:101])),
  "Zinc" = as.numeric(gsub(",", ".", cowg[50,3:101])),
  "Zinc_68Zn" = rep(0, 101-2),
  "Zinc_67Zn" = rep(0, 101-2),
  "Zinc_66Zn" = ifelse(is.na(as.numeric(gsub(",", ".", cowg[50,3:101]))), 0,1)
  )
```

```{r}
write_delim(COWG, here("processed","recent_COWG_daily.csv"), delim = ";")
```

```{r}
all_months <- seq(
  from = as.Date(format(min(COWG$Dates), "%Y-%m-01")),
  to   = as.Date(format(max(COWG$Dates), "%Y-%m-01")),
  by = "month"
)
all_months_df <- data.frame(Dates = all_months)

COWG$MonthDate <- as.Date(format(COWG$Dates, "%Y-%m-01"))
COWG <- all_months_df %>%
  left_join(COWG, by = c("Dates" = "MonthDate"))
```

```{r}
mean_COWG <- COWG %>%
  mutate(
    month = month(as.POSIXlt(Dates, format="%Y-%m-%d")),
    year = year(as.POSIXlt(Dates, format="%Y-%m-%d"))
  ) %>%
  group_by(month, year) %>%
  summarise(Temperature = mean(Temperature),
            pH = mean(pH),
            Eh = mean(Eh),
            Conductivité = mean(Conductivité),
            O2 = mean(O2),
            O2_HACH = max(O2_HACH),
            O2_Colorimétrie = max(O2_Colorimétrie),
            O2_Mettler = max(O2_Mettler),
            Aluminium = mean(Aluminium),
            Antimoine = mean(Antimoine),
            Antimoine_123Sb = max(Antimoine_123Sb),
            Antimoine_121Sb = max(Antimoine_121Sb),
            Arséniate = mean(Arséniate),
            Arsénite = mean(Arsénite),
            Arsenic_Total = mean(Arsenic_Total),
            Baryum = mean(Baryum),
            Baryum_138Ba = max(Baryum_138Ba),
            Baryum_137Ba = max(Baryum_137Ba),
            Baryum_136Ba = max(Baryum_136Ba),
            Bore = mean(Bore),
            Cadmium = mean(Cadmium),
            Cadmium_114Cd = max(Cadmium_114Cd),
            Cadmium_111Cd = max(Cadmium_111Cd),
            Calcium = mean(Calcium),
            Calcium_44Ca = max(Calcium_44Ca),
            Calcium_43Ca = max(Calcium_43Ca),
            Césium = mean(Césium),
            Chrome = mean(Chrome),
            Chrome_53Cr = max(Chrome_53Cr),
            Chrome_52Cr = max(Chrome_52Cr),
            Cobalt = mean(Cobalt),
            Cuivre = mean(Cuivre),
            Cuivre_65Cu = max(Cuivre_65Cu),
            Cuivre_63Cu = max(Cuivre_63Cu),
            Fer_Total = mean(Fer_Total),
            Lanthane = mean(Lanthane),
            Magnésium = mean(Magnésium),
            Nickel = mean(Nickel),
            Nickel_62Ni = max(Nickel_62Ni),
            Nickel_60Ni = max(Nickel_60Ni),
            Plomb = mean(Plomb),
            Plomb_208Pb = max(Plomb_208Pb),
            Plomb_207Pb = max(Plomb_207Pb),
            Plomb_206Pb = max(Plomb_206Pb),
            Rubidium = mean(Rubidium),
            Sodium = mean(Sodium),
            Souffre = mean(Souffre),
            Strontium = mean(Strontium),
            Strontium_88Sr = max(Strontium_88Sr),
            Strontium_86Sr = max(Strontium_86Sr),
            Thallium = mean(Thallium),
            Thallium_205Tl = max(Thallium_205Tl),
            Thallium_203Tl = max(Thallium_203Tl),
            Titane = mean(Titane),
            Titane_49Ti = max(Titane_49Ti),
            Titane_47Ti = max(Titane_47Ti),
            Vanadium = mean(Vanadium),
            Yttrium = mean(Yttrium),
            Zinc = mean(Zinc),
            Zinc_68Zn = max(Zinc_68Zn),
            Zinc_67Zn = max(Zinc_67Zn),
            Zinc_66Zn = max(Zinc_66Zn)
            ) %>%
  mutate(MonthDate = as.Date(paste(year, month, "01", sep = "-")))
```

```{r, warning=FALSE}
monthly_COWG <- COWG %>%
  mutate(
    month = month(Dates),
    year = year(Dates)
  ) %>%
  left_join(mean_COWG, by = c("month", "year")) %>%
  select(-c(Dates.y, ends_with(".x"), month, year, MonthDate)) %>% 
  distinct() %>%
  rename_with(~ gsub("\\.y$", "", .x))
```

```{r}
write_delim(monthly_COWG, here("processed","recent_COWG.csv"), delim = ";")
```

