---
title: "dates processing"
author: "CLETZ Laura"
date: "27/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(tibble)
here::i_am("Data_Processing/dates_processing.Rmd")
library(here)
```

```{r}
S1 <- read.table(here("processed","Source_S1.csv"), dec=".", sep=";", header=T) 
S1$dates <- as.Date(S1$dates, format = "%Y-%m-%d")
```

```{r}
S5 <- read.table(here("processed","S5.csv"), dec=".", sep=";", header=T) 
S5$dates <- as.Date(S5$dates, format = "%Y-%m-%d")
```

```{r}
COWG <- read.table(here("processed","COWG.csv"), dec=".", sep=";", header=T) 
COWG$dates <- as.Date(COWG$dates, format = "%Y-%m-%d")
```

```{r}
recent_COWG <- read.table(here("processed","recent_COWG.csv"), dec=".", sep=";", header=T)
recent_COWG$dates <- as.Date(recent_COWG$dates, format = "%Y-%m-%d")
```

```{r}
long_COWG <- COWG %>% bind_rows(recent_COWG)
```

```{r}
GAL <- read.table(here("processed","GAL.csv"), dec=".", sep=";", header=T) 
GAL$dates <- as.Date(GAL$dates, format = "%Y-%m-%d")
```

```{r}
Confluence <- read.table(here("processed","Confluence.csv"), dec=".", sep=";", header=T)
Confluence$dates <- as.Date(Confluence$dates, format = "%Y-%m-%d")
```

```{r}
Amous <- read.table(here("processed","Amous_1200.csv"), dec=".", sep=";", header=T)
Amous$dates <- as.Date(Amous$dates, format = "%Y-%m-%d")
```

```{r}
dates_processing <- function(df) {

  df$corrected_dates <- as.Date(df$dates[1], format = "%Y-%m-%d")
  df <- df %>% relocate(corrected_dates)
  
  for (row in 2:nrow(df)) {
    df$corrected_dates[row] <- NA
  }

  while (any(is.na(df$corrected_dates))) {
    for (row in 2:nrow(df)) {
      if (is.na(df$corrected_dates[row])) {
        diff <- difftime(df$dates[row], df$corrected_dates[row - 1], units = "days")

        if (diff >= 60) {
          new_row <- data.frame(dates = NA, corrected_dates = df$corrected_dates[row - 1] + 30)
          df <- bind_rows(df[1:(row - 1), ], new_row, df[row:nrow(df), ]) %>%
            arrange(corrected_dates)
          break
          
        } else {
          df$corrected_dates[row] <- df$corrected_dates[row - 1] + 30
        }
      }
    }
  }

  return(df)
}
```

```{r}
S1 <- dates_processing(S1)
S5 <- dates_processing(S5)
long_COWG <- dates_processing(long_COWG)
GAL <- dates_processing(GAL)
Confluence <- dates_processing(Confluence)
Amous <- dates_processing(Amous)
```


```{r}
undetermined_method <- function(df){
  
  levels(df$o2_method) <- c(levels(df$o2_method), "undetermined_o2_method")
  df$o2_method[ is.na( df$o2_method ) ] <- "undetermined_o2_method"
  
  levels(df$antimony_method) <- c(levels(df$antimony_method), "undetermined_antimony_method")
  df$antimony_method[ is.na( df$antimony_method ) ] <- "undetermined_antimony_method"
  
  levels(df$baryum_method) <- c(levels(df$baryum_method), "undetermined_baryum_method")
  df$baryum_method[ is.na( df$baryum_method ) ] <- "undetermined_baryum_method"
  
  levels(df$cadmium_method) <- c(levels(df$cadmium_method), "undetermined_cadmium_method")
  df$cadmium_method[ is.na( df$cadmium_method ) ] <- "undetermined_cadmium_method"
  
  levels(df$calcium_method) <- c(levels(df$calcium_method), "undetermined_calcium_method")
  df$calcium_method[ is.na( df$calcium_method ) ] <- "undetermined_calcium_method"
  
  levels(df$chromium_method) <- c(levels(df$chromium_method), "undetermined_chromium_method")
  df$chromium_method[ is.na( df$chromium_method ) ] <- "undetermined_chromium_method"
  
  levels(df$copper_method) <- c(levels(df$copper_method), "undetermined_copper_method")
  df$copper_method[ is.na( df$copper_method ) ] <- "undetermined_copper_method"
  
  levels(df$tin_method) <- c(levels(df$tin_method), "undetermined_tin_method")
  df$tin_method[ is.na( df$tin_method ) ] <- "undetermined_tin_method"
  
  levels(df$molybdenum_method) <- c(levels(df$molybdenum_method), "undetermined_molybdenum_method")
  df$molybdenum_method[ is.na( df$molybdenum_method ) ] <- "undetermined_molybdenum_method"
  
  levels(df$nickel_method) <- c(levels(df$nickel_method), "undetermined_nickel_method")
  df$nickel_method[ is.na( df$nickel_method ) ] <- "undetermined_nickel_method"
  
  levels(df$lead_method) <- c(levels(df$lead_method), "undetermined_lead_method")
  df$lead_method[ is.na( df$lead_method ) ] <- "undetermined_lead_method"
  
  levels(df$strontium_method) <- c(levels(df$strontium_method), "undetermined_strontium_method")
  df$strontium_method[ is.na( df$strontium_method ) ] <- "undetermined_strontium_method"
  
  levels(df$thallium_method) <- c(levels(df$thallium_method), "undetermined_thallium_method")
  df$thallium_method[ is.na( df$thallium_method ) ] <- "undetermined_thallium_method"
  
  levels(df$titanium_method) <- c(levels(df$titanium_method), "undetermined_titanium_method")
  df$titanium_method[ is.na( df$titanium_method ) ] <- "undetermined_titanium_method"
  
  levels(df$zinc_method) <- c(levels(df$zinc_method), "undetermined_zinc_method")
  df$zinc_method[ is.na( df$zinc_method ) ] <- "undetermined_zinc_method"
  
  return(df)
}
```

```{r}
S1 <- undetermined_method(S1)
S5 <- undetermined_method(S5)
COWG <- undetermined_method(COWG)
GAL <- undetermined_method(GAL)
Confluence <- undetermined_method(Confluence)
Amous <- undetermined_method(Amous)
```

```{r}
write_delim(S1, here("processed","Source_S1.csv"), delim=";")
write_delim(S5, here("processed","S5.csv"), delim=";")
write_delim(long_COWG, here("processed","COWG.csv"), delim=";")
write_delim(GAL, here("processed","GAL.csv"), delim=";")
write_delim(Confluence, here("processed","Confluence.csv"), delim=";")
write_delim(Amous, here("processed","Amous_1200.csv"), delim=";")
```

