---
title: "Datas processing"
author: "chloride_ionETZ Laura"
date: "02/06/2025"
output: pdf_document
---

```{r setup, inchloride_ionude=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(dplyr)
library(tidyverse)
here::i_am("Data_Processing/tidy_datas.Rmd")
library(here)
```
Each .csv file from the folder `/tables` corresponds with one exported sheet from the .xlsm file:
```{r, warning=FALSE}
files <- list.files(here("raw_data","tables"), pattern = "\\.csv$", full.names = TRUE)
data <- data.frame()
for(file in files){
  file <- read_delim(file, na = c("", "NA"), col_names = FALSE, show_col_types = FALSE)
  file <- file %>% select(1:8)
  file <- file[1:86,]
  data <- rbind(data, file)
}
```

chloride_ioneaning dates format:
```{r}
get_dates <- grep('/', data$X1)
dates <- data$X1[get_dates]

parse_date_time_robust <- function(x){
   parse_date_time(
     x,
     orders = c('dmy','dmY','mdy','mdY','ymd','y-md'),
     quiet=TRUE
   )
}
dates <- parse_date_time_robust(dates)
```

# Creating a data.frame for each variables

```{r}
temperature <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='T')],
  "S5" = data$X3[which(data$X1=='T')],
  "COWG" = data$X5[which(data$X1=='T')],
  "GAL" = data$X6[which(data$X1=='T')],
  "Confluence" = data$X7[which(data$X1=='T')],
  "Amous" = data$X8[which(data$X1=='T')]
) %>%
  arrange(dates)
```

```{r}
ph <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='pH')],
  "S5" = data$X3[which(data$X1=='pH')],
  "COWG" = data$X5[which(data$X1=='pH')],
  "GAL" = data$X6[which(data$X1=='pH')],
  "Confluence" = data$X7[which(data$X1=='pH')],
  "Amous" = data$X8[which(data$X1=='pH')]
) %>%
  arrange(dates)
```

```{r}
eh <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Eh')],
  "S5" = data$X3[which(data$X1=='Eh')],
  "COWG" = data$X5[which(data$X1=='Eh')],
  "GAL" = data$X6[which(data$X1=='Eh')],
  "Confluence" = data$X7[which(data$X1=='Eh')],
  "Amous" = data$X8[which(data$X1=='Eh')]
) %>%
  arrange(dates)
```

```{r}
conductivity <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Conductivité')],
  "S5" = data$X3[which(data$X1=='Conductivité')],
  "COWG" = data$X5[which(data$X1=='Conductivité')],
  "GAL" = data$X6[which(data$X1=='Conductivité')],
  "Confluence" = data$X7[which(data$X1=='Conductivité')],
  "Amous" = data$X8[which(data$X1=='Conductivité')]
) %>%
  arrange(dates)
```

```{r}
o2 <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X4[which(data$X2=='colorimétrie - ppm')]), data$X4[which(data$X2=='electrode Mettler - ppm')], data$X4[which(data$X2=='colorimétrie - ppm')]), data$X4[which(data$X2=='electrode HACH - ppm')]),
  "S5" = ifelse(is.na(data$X3[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X3[which(data$X2=='colorimétrie - ppm')]), data$X3[which(data$X2=='electrode Mettler - ppm')], data$X3[which(data$X2=='colorimétrie - ppm')]), data$X3[which(data$X2=='electrode HACH - ppm')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X5[which(data$X2=='colorimétrie - ppm')]), data$X5[which(data$X2=='electrode Mettler - ppm')], data$X5[which(data$X2=='colorimétrie - ppm')]), data$X5[which(data$X2=='electrode HACH - ppm')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X6[which(data$X2=='colorimétrie - ppm')]), data$X6[which(data$X2=='electrode Mettler - ppm')], data$X6[which(data$X2=='colorimétrie - ppm')]), data$X6[which(data$X2=='electrode HACH - ppm')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X7[which(data$X2=='colorimétrie - ppm')]), data$X7[which(data$X2=='electrode Mettler - ppm')], data$X7[which(data$X2=='colorimétrie - ppm')]), data$X7[which(data$X2=='electrode HACH - ppm')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X2=='electrode HACH - ppm')]), ifelse(is.na(data$X8[which(data$X2=='colorimétrie - ppm')]), data$X8[which(data$X2=='electrode Mettler - ppm')], data$X8[which(data$X2=='colorimétrie - ppm')]), data$X8[which(data$X2=='electrode HACH - ppm')]),
  "S1_hach" = ifelse(is.na(data$X4[which(data$X2=='electrode HACH - ppm')]),0,1),
  "S5_hach" = ifelse(is.na(data$X3[which(data$X2=='electrode HACH - ppm')]),0,1),
  "COWG_hach" = ifelse(is.na(data$X5[which(data$X2=='electrode HACH - ppm')]),0,1),
  "GAL_hach" = ifelse(is.na(data$X6[which(data$X2=='electrode HACH - ppm')]),0,1),
  "Confluence_hach" = ifelse(is.na(data$X7[which(data$X2=='electrode HACH - ppm')]),0,1),
  "Amous_hach" = ifelse(is.na(data$X8[which(data$X2=='electrode HACH - ppm')]),0,1),
  "S1_colorimetrie" = ifelse(is.na(data$X4[which(data$X2=='colorimétrie - ppm')]),0,1),
  "S5_colorimetrie" = ifelse(is.na(data$X3[which(data$X2=='colorimétrie - ppm')]),0,1),
  "COWG_colorimetrie" = ifelse(is.na(data$X5[which(data$X2=='colorimétrie - ppm')]),0,1),
  "GAL_colorimetrie" = ifelse(is.na(data$X6[which(data$X2=='colorimétrie - ppm')]),0,1),
  "Confluence_colorimetrie" = ifelse(is.na(data$X7[which(data$X2=='colorimétrie - ppm')]),0,1),
  "Amous_colorimetrie" = ifelse(is.na(data$X8[which(data$X2=='colorimétrie - ppm')]),0,1),
  "S1_mettler" = ifelse(is.na(data$X4[which(data$X2=='electrode Mettler - ppm')]),0,1),
  "S5_mettler" = ifelse(is.na(data$X3[which(data$X2=='electrode Mettler - ppm')]),0,1),
  "COWG_mettler" = ifelse(is.na(data$X5[which(data$X2=='electrode Mettler - ppm')]),0,1),
  "GAL_mettler" = ifelse(is.na(data$X6[which(data$X2=='electrode Mettler - ppm')]),0,1),
  "Confluence_mettler" = ifelse(is.na(data$X7[which(data$X2=='electrode Mettler - ppm')]),0,1),
  "Amous_mettler" = ifelse(is.na(data$X8[which(data$X2=='electrode Mettler - ppm')]),0,1)
) %>%
  arrange(dates)
```

```{r}
sulfate <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='SO42-')],
  "S5" = data$X3[which(data$X1=='SO42-')],
  "COWG" = data$X5[which(data$X1=='SO42-')],
  "GAL" = data$X6[which(data$X1=='SO42-')],
  "Confluence" = data$X7[which(data$X1=='SO42-')],
  "Amous" = data$X8[which(data$X1=='SO42-')]
) %>%
  arrange(dates)
```

```{r}
feII <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Fe II')],
  "S5" = data$X3[which(data$X1=='Fe II')],
  "COWG" = data$X5[which(data$X1=='Fe II')],
  "GAL" = data$X6[which(data$X1=='Fe II')],
  "Confluence" = data$X7[which(data$X1=='Fe II')],
  "Amous" = data$X8[which(data$X1=='Fe II')]
) %>%
  arrange(dates)
```

```{r}
total_iron <- data.frame(
  "dates" = dates[-which(dates==as.Date("2019-01-28 UTC"))],
  "S1" = data$X4[which(data$X1=='Fe total par AA')],
  "S5" = data$X3[which(data$X1=='Fe total par AA')],
  "COWG" = data$X5[which(data$X1=='Fe total par AA')],
  "GAL" = data$X6[which(data$X1=='Fe total par AA')],
  "Confluence" = data$X7[which(data$X1=='Fe total par AA')],
  "Amous" = data$X8[which(data$X1=='Fe total par AA')]
) %>%
  arrange(dates)
total_iron <- total_iron %>% bind_rows(
  data.frame(
    dates = as.Date("2019-01-28", format = "%Y-%m-%d"), 
    S1 = NA,
    S5 = NA,
    COWG = NA,
    GAL = NA,
    Confluence = NA,
    Amous = NA
    )
  )
```

```{r}
chloride_ion <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Cl-')],
  "S5" = data$X3[which(data$X1=='Cl-')],
  "COWG" = data$X5[which(data$X1=='Cl-')],
  "GAL" = data$X6[which(data$X1=='Cl-')],
  "Confluence" = data$X7[which(data$X1=='Cl-')],
  "Amous" = data$X8[which(data$X1=='Cl-')]
) %>%
  arrange(dates)
```

```{r}
nitrate <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='NO3-')],
  "S5" = data$X3[which(data$X1=='NO3-')],
  "COWG" = data$X5[which(data$X1=='NO3-')],
  "GAL" = data$X6[which(data$X1=='NO3-')],
  "Confluence" = data$X7[which(data$X1=='NO3-')],
  "Amous" = data$X8[which(data$X1=='NO3-')]
) %>%
  arrange(dates)
```

```{r}
calcium_ion <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Ca2+')],
  "S5" = data$X3[which(data$X1=='Ca2+')],
  "COWG" = data$X5[which(data$X1=='Ca2+')],
  "GAL" = data$X6[which(data$X1=='Ca2+')],
  "Confluence" = data$X7[which(data$X1=='Ca2+')],
  "Amous" = data$X8[which(data$X1=='Ca2+')]
) %>%
  arrange(dates)
```

```{r}
magnesium_ion <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Mg2+')],
  "S5" = data$X3[which(data$X1=='Mg2+')],
  "COWG" = data$X5[which(data$X1=='Mg2+')],
  "GAL" = data$X6[which(data$X1=='Mg2+')],
  "Confluence" = data$X7[which(data$X1=='Mg2+')],
  "Amous" = data$X8[which(data$X1=='Mg2+')]
) %>%
  arrange(dates)
```

```{r}
sodium_ion <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Na+')],
  "S5" = data$X3[which(data$X1=='Na+')],
  "COWG" = data$X5[which(data$X1=='Na+')],
  "GAL" = data$X6[which(data$X1=='Na+')],
  "Confluence" = data$X7[which(data$X1=='Na+')],
  "Amous" = data$X8[which(data$X1=='Na+')]
) %>%
  arrange(dates)
```

```{r}
potassium_ion <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='K+')],
  "S5" = data$X3[which(data$X1=='K+')],
  "COWG" = data$X5[which(data$X1=='K+')],
  "GAL" = data$X6[which(data$X1=='K+')],
  "Confluence" = data$X7[which(data$X1=='K+')],
  "Amous" = data$X8[which(data$X1=='K+')]
) %>%
  arrange(dates)
```

```{r}
fluoride <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='F-')],
  "S5" = data$X3[which(data$X1=='F-')],
  "COWG" = data$X5[which(data$X1=='F-')],
  "GAL" = data$X6[which(data$X1=='F-')],
  "Confluence" = data$X7[which(data$X1=='F-')],
  "Amous" = data$X8[which(data$X1=='F-')]
) %>%
  arrange(dates)
```

```{r}
bromide <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Br-')],
  "S5" = data$X3[which(data$X1=='Br-')],
  "COWG" = data$X5[which(data$X1=='Br-')],
  "GAL" = data$X6[which(data$X1=='Br-')],
  "Confluence" = data$X7[which(data$X1=='Br-')],
  "Amous" = data$X8[which(data$X1=='Br-')]
) %>%
  arrange(dates)
```

```{r}
asIII <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='As III')],
  "S5" = data$X3[which(data$X1=='As III')],
  "COWG" = data$X5[which(data$X1=='As III')],
  "GAL" = data$X6[which(data$X1=='As III')],
  "Confluence" = data$X7[which(data$X1=='As III')],
  "Amous" = data$X8[which(data$X1=='As III')]
) %>%
  arrange(dates)
```

```{r}
asV <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='As V')],
  "S5" = data$X3[which(data$X1=='As V')],
  "COWG" = data$X5[which(data$X1=='As V')],
  "GAL" = data$X6[which(data$X1=='As V')],
  "Confluence" = data$X7[which(data$X1=='As V')],
  "Amous" = data$X8[which(data$X1=='As V')]
) %>%
  arrange(dates)
```

```{r}
total_arsenic <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='As total')]), data$X4[which(data$X1=='75As')], data$X4[which(data$X1=='As total')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='As total')]), data$X3[which(data$X1=='75As')], data$X3[which(data$X1=='As total')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='As total')]), data$X5[which(data$X1=='75As')], data$X5[which(data$X1=='As total')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='As total')]), data$X6[which(data$X1=='75As')], data$X6[which(data$X1=='As total')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='As total')]), data$X7[which(data$X1=='75As')], data$X7[which(data$X1=='As total')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='As total')]), data$X8[which(data$X1=='75As')], data$X8[which(data$X1=='As total')])
) %>%
  arrange(dates)
```

```{r}
cobalt <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='59Co')],
  "S5" = data$X3[which(data$X1=='59Co')],
  "COWG" = data$X5[which(data$X1=='59Co')],
  "GAL" = data$X6[which(data$X1=='59Co')],
  "Confluence" = data$X7[which(data$X1=='59Co')],
  "Amous" = data$X8[which(data$X1=='59Co')]
) %>%
  arrange(dates)
```

```{r}
sulfur <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='34S')],
  "S5" = data$X3[which(data$X1=='34S')],
  "COWG" = data$X5[which(data$X1=='34S')],
  "GAL" = data$X6[which(data$X1=='34S')],
  "Confluence" = data$X7[which(data$X1=='34S')],
  "Amous" = data$X8[which(data$X1=='34S')]
) %>%
  arrange(dates)
```

```{r}
bore <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='11B')],
  "S5" = data$X3[which(data$X1=='11B')],
  "COWG" = data$X5[which(data$X1=='11B')],
  "GAL" = data$X6[which(data$X1=='11B')],
  "Confluence" = data$X7[which(data$X1=='11B')],
  "Amous" = data$X8[which(data$X1=='11B')]
) %>%
  arrange(dates)
```

```{r}
sodium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Na')],
  "S5" = data$X3[which(data$X1=='Na')],
  "COWG" = data$X5[which(data$X1=='Na')],
  "GAL" = data$X6[which(data$X1=='Na')],
  "Confluence" = data$X7[which(data$X1=='Na')],
  "Amous" = data$X8[which(data$X1=='Na')]
) %>%
  arrange(dates)
```

```{r}
magnesium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='Mg')],
  "S5" = data$X3[which(data$X1=='Mg')],
  "COWG" = data$X5[which(data$X1=='Mg')],
  "GAL" = data$X6[which(data$X1=='Mg')],
  "Confluence" = data$X7[which(data$X1=='Mg')],
  "Amous" = data$X8[which(data$X1=='Mg')]
) %>%
  arrange(dates)
```

```{r}
aluminium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='27Al')],
  "S5" = data$X3[which(data$X1=='27Al')],
  "COWG" = data$X5[which(data$X1=='27Al')],
  "GAL" = data$X6[which(data$X1=='27Al')],
  "Confluence" = data$X7[which(data$X1=='27Al')],
  "Amous" = data$X8[which(data$X1=='27Al')]
) %>%
  arrange(dates)
```

```{r}
copper <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='65Cu')]), data$X4[which(data$X1=='63Cu')], data$X4[which(data$X1=='65Cu')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='65Cu')]), data$X3[which(data$X1=='63Cu')], data$X3[which(data$X1=='65Cu')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='65Cu')]), data$X5[which(data$X1=='63Cu')], data$X5[which(data$X1=='65Cu')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='65Cu')]), data$X6[which(data$X1=='63Cu')], data$X6[which(data$X1=='65Cu')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='65Cu')]), data$X7[which(data$X1=='63Cu')], data$X4[which(data$X7=='65Cu')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='65Cu')]), data$X8[which(data$X1=='63Cu')], data$X8[which(data$X1=='65Cu')]),
  "S1_65Cu" = ifelse(is.na(data$X4[which(data$X1=='65Cu')]),0,1),
  "S5_65Cu" = ifelse(is.na(data$X3[which(data$X1=='65Cu')]),0,1),
  "COWG_65Cu" = ifelse(is.na(data$X5[which(data$X1=='65Cu')]),0,1),
  "GAL_65Cu" = ifelse(is.na(data$X6[which(data$X1=='65Cu')]),0,1),
  "Confluence_65Cu" = ifelse(is.na(data$X7[which(data$X1=='65Cu')]),0,1),
  "Amous_65Cu" = ifelse(is.na(data$X8[which(data$X1=='65Cu')]),0,1),
  "S1_63Cu" = ifelse(is.na(data$X4[which(data$X1=='63Cu')]),0,1),
  "S5_63Cu" = ifelse(is.na(data$X3[which(data$X1=='63Cu')]),0,1),
  "COWG_63Cu" = ifelse(is.na(data$X5[which(data$X1=='63Cu')]),0,1),
  "GAL_63Cu" = ifelse(is.na(data$X6[which(data$X1=='63Cu')]),0,1),
  "Confluence_63Cu" = ifelse(is.na(data$X7[which(data$X1=='63Cu')]),0,1),
  "Amous_63Cu" = ifelse(is.na(data$X8[which(data$X1=='63Cu')]),0,1)
) %>%
  arrange(dates)
```

```{r}
calcium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='44Ca')]), data$X4[which(data$X1=='43Ca')], data$X4[which(data$X1=='44Ca')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='44Ca')]), data$X3[which(data$X1=='43Ca')], data$X3[which(data$X1=='44Ca')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='44Ca')]), data$X5[which(data$X1=='43Ca')], data$X5[which(data$X1=='44Ca')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='44Ca')]), data$X6[which(data$X1=='43Ca')], data$X6[which(data$X1=='44Ca')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='44Ca')]), data$X7[which(data$X1=='43Ca')], data$X4[which(data$X7=='44Ca')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='44Ca')]), data$X8[which(data$X1=='43Ca')], data$X8[which(data$X1=='44Ca')]),
  "S1_44Ca" = ifelse(is.na(data$X4[which(data$X1=='44Ca')]),0,1),
  "S5_44Ca" = ifelse(is.na(data$X3[which(data$X1=='44Ca')]),0,1),
  "COWG_44Ca" = ifelse(is.na(data$X5[which(data$X1=='44Ca')]),0,1),
  "GAL_44Ca" = ifelse(is.na(data$X6[which(data$X1=='44Ca')]),0,1),
  "Confluence_44Ca" = ifelse(is.na(data$X7[which(data$X1=='44Ca')]),0,1),
  "Amous_44Ca" = ifelse(is.na(data$X8[which(data$X1=='44Ca')]),0,1),
  "S1_43Ca" = ifelse(is.na(data$X4[which(data$X1=='43Ca')]),0,1),
  "S5_43Ca" = ifelse(is.na(data$X3[which(data$X1=='43Ca')]),0,1),
  "COWG_43Ca" = ifelse(is.na(data$X5[which(data$X1=='43Ca')]),0,1),
  "GAL_43Ca" = ifelse(is.na(data$X6[which(data$X1=='43Ca')]),0,1),
  "Confluence_43Ca" = ifelse(is.na(data$X7[which(data$X1=='43Ca')]),0,1),
  "Amous_43Ca" = ifelse(is.na(data$X8[which(data$X1=='43Ca')]),0,1)
) %>%
  arrange(dates)
```

```{r}
titanium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='49Ti')]), data$X4[which(data$X1=='47Ti')], data$X4[which(data$X1=='49Ti')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='49Ti')]), data$X3[which(data$X1=='47Ti')], data$X3[which(data$X1=='49Ti')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='49Ti')]), data$X5[which(data$X1=='47Ti')], data$X5[which(data$X1=='49Ti')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='49Ti')]), data$X6[which(data$X1=='47Ti')], data$X6[which(data$X1=='49Ti')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='49Ti')]), data$X7[which(data$X1=='47Ti')], data$X4[which(data$X7=='49Ti')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='49Ti')]), data$X8[which(data$X1=='47Ti')], data$X8[which(data$X1=='49Ti')]),
  "S1_49Ti" = ifelse(is.na(data$X4[which(data$X1=='49Ti')]),0,1),
  "S5_49Ti" = ifelse(is.na(data$X3[which(data$X1=='49Ti')]),0,1),
  "COWG_49Ti" = ifelse(is.na(data$X5[which(data$X1=='49Ti')]),0,1),
  "GAL_49Ti" = ifelse(is.na(data$X6[which(data$X1=='49Ti')]),0,1),
  "Confluence_49Ti" = ifelse(is.na(data$X7[which(data$X1=='49Ti')]),0,1),
  "Amous_49Ti" = ifelse(is.na(data$X8[which(data$X1=='49Ti')]),0,1),
  "S1_47Ti" = ifelse(is.na(data$X4[which(data$X1=='47Ti')]),0,1),
  "S5_47Ti" = ifelse(is.na(data$X3[which(data$X1=='47Ti')]),0,1),
  "COWG_47Ti" = ifelse(is.na(data$X5[which(data$X1=='47Ti')]),0,1),
  "GAL_47Ti" = ifelse(is.na(data$X6[which(data$X1=='47Ti')]),0,1),
  "Confluence_47Ti" = ifelse(is.na(data$X7[which(data$X1=='47Ti')]),0,1),
  "Amous_47Ti" = ifelse(is.na(data$X8[which(data$X1=='47Ti')]),0,1)
) %>%
  arrange(dates)
```

```{r}
vanadium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='51V')],
  "S5" = data$X3[which(data$X1=='51V')],
  "COWG" = data$X5[which(data$X1=='51V')],
  "GAL" = data$X6[which(data$X1=='51V')],
  "Confluence" = data$X7[which(data$X1=='51V')],
  "Amous" = data$X8[which(data$X1=='51V')]
) %>%
  arrange(dates)
```

```{r}
rubidium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='85Rb')],
  "S5" = data$X3[which(data$X1=='85Rb')],
  "COWG" = data$X5[which(data$X1=='85Rb')],
  "GAL" = data$X6[which(data$X1=='85Rb')],
  "Confluence" = data$X7[which(data$X1=='85Rb')],
  "Amous" = data$X8[which(data$X1=='85Rb')]
) %>%
  arrange(dates)
```

```{r}
yttrium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='89Y')],
  "S5" = data$X3[which(data$X1=='89Y')],
  "COWG" = data$X5[which(data$X1=='89Y')],
  "GAL" = data$X6[which(data$X1=='89Y')],
  "Confluence" = data$X7[which(data$X1=='89Y')],
  "Amous" = data$X8[which(data$X1=='89Y')]
) %>%
  arrange(dates)
```

```{r}
zirconium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='90Zr')],
  "S5" = data$X3[which(data$X1=='90Zr')],
  "COWG" = data$X5[which(data$X1=='90Zr')],
  "GAL" = data$X6[which(data$X1=='90Zr')],
  "Confluence" = data$X7[which(data$X1=='90Zr')],
  "Amous" = data$X8[which(data$X1=='90Zr')]
) %>%
  arrange(dates)
```

```{r}
caesium <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='133Cs')],
  "S5" = data$X3[which(data$X1=='133Cs')],
  "COWG" = data$X5[which(data$X1=='133Cs')],
  "GAL" = data$X6[which(data$X1=='133Cs')],
  "Confluence" = data$X7[which(data$X1=='133Cs')],
  "Amous" = data$X8[which(data$X1=='133Cs')]
) %>%
  arrange(dates)
```

```{r}
chromium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='53Cr')]), data$X4[which(data$X1=='52Cr')], data$X4[which(data$X1=='53Cr')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='53Cr')]), data$X3[which(data$X1=='52Cr')], data$X3[which(data$X1=='53Cr')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='53Cr')]), data$X5[which(data$X1=='52Cr')], data$X5[which(data$X1=='53Cr')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='53Cr')]), data$X6[which(data$X1=='52Cr')], data$X6[which(data$X1=='53Cr')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='53Cr')]), data$X7[which(data$X1=='52Cr')], data$X4[which(data$X7=='53Cr')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='53Cr')]), data$X8[which(data$X1=='52Cr')], data$X8[which(data$X1=='53Cr')]),
  "S1_53Cr" = ifelse(is.na(data$X4[which(data$X1=='53Cr')]),0,1),
  "S5_53Cr" = ifelse(is.na(data$X3[which(data$X1=='53Cr')]),0,1),
  "COWG_53Cr" = ifelse(is.na(data$X5[which(data$X1=='53Cr')]),0,1),
  "GAL_53Cr" = ifelse(is.na(data$X6[which(data$X1=='53Cr')]),0,1),
  "Confluence_53Cr" = ifelse(is.na(data$X7[which(data$X1=='53Cr')]),0,1),
  "Amous_53Cr" = ifelse(is.na(data$X8[which(data$X1=='53Cr')]),0,1),
  "S1_52Cr" = ifelse(is.na(data$X4[which(data$X1=='52Cr')]),0,1),
  "S5_52Cr" = ifelse(is.na(data$X3[which(data$X1=='52Cr')]),0,1),
  "COWG_52Cr" = ifelse(is.na(data$X5[which(data$X1=='52Cr')]),0,1),
  "GAL_52Cr" = ifelse(is.na(data$X6[which(data$X1=='52Cr')]),0,1),
  "Confluence_52Cr" = ifelse(is.na(data$X7[which(data$X1=='52Cr')]),0,1),
  "Amous_52Cr" = ifelse(is.na(data$X8[which(data$X1=='52Cr')]),0,1)
) %>%
  arrange(dates)
```

```{r}
molybdenum <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='97Mo')]), data$X4[which(data$X1=='95Mo')], data$X4[which(data$X1=='97Mo')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='97Mo')]), data$X3[which(data$X1=='95Mo')], data$X3[which(data$X1=='97Mo')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='97Mo')]), data$X5[which(data$X1=='95Mo')], data$X5[which(data$X1=='97Mo')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='97Mo')]), data$X6[which(data$X1=='95Mo')], data$X6[which(data$X1=='97Mo')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='97Mo')]), data$X7[which(data$X1=='95Mo')], data$X4[which(data$X7=='97Mo')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='97Mo')]), data$X8[which(data$X1=='95Mo')], data$X8[which(data$X1=='97Mo')]),
  "S1_97Mo" = ifelse(is.na(data$X4[which(data$X1=='97Mo')]),0,1),
  "S5_97Mo" = ifelse(is.na(data$X3[which(data$X1=='97Mo')]),0,1),
  "COWG_97Mo" = ifelse(is.na(data$X5[which(data$X1=='97Mo')]),0,1),
  "GAL_97Mo" = ifelse(is.na(data$X6[which(data$X1=='97Mo')]),0,1),
  "Confluence_97Mo" = ifelse(is.na(data$X7[which(data$X1=='97Mo')]),0,1),
  "Amous_97Mo" = ifelse(is.na(data$X8[which(data$X1=='97Mo')]),0,1),
  "S1_95Mo" = ifelse(is.na(data$X4[which(data$X1=='95Mo')]),0,1),
  "S5_95Mo" = ifelse(is.na(data$X3[which(data$X1=='95Mo')]),0,1),
  "COWG_95Mo" = ifelse(is.na(data$X5[which(data$X1=='95Mo')]),0,1),
  "GAL_95Mo" = ifelse(is.na(data$X6[which(data$X1=='95Mo')]),0,1),
  "Confluence_95Mo" = ifelse(is.na(data$X7[which(data$X1=='95Mo')]),0,1),
  "Amous_95Mo" = ifelse(is.na(data$X8[which(data$X1=='95Mo')]),0,1)
) %>%
  arrange(dates)
```

```{r}
tin <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='120Sn')]), data$X4[which(data$X1=='118Sn')], data$X4[which(data$X1=='120Sn')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='120Sn')]), data$X3[which(data$X1=='118Sn')], data$X3[which(data$X1=='120Sn')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='120Sn')]), data$X5[which(data$X1=='118Sn')], data$X5[which(data$X1=='120Sn')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='120Sn')]), data$X6[which(data$X1=='118Sn')], data$X6[which(data$X1=='120Sn')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='120Sn')]), data$X7[which(data$X1=='118Sn')], data$X4[which(data$X7=='120Sn')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='120Sn')]), data$X8[which(data$X1=='118Sn')], data$X8[which(data$X1=='120Sn')]),
  "S1_120Sn" = ifelse(is.na(data$X4[which(data$X1=='120Sn')]),0,1),
  "S5_120Sn" = ifelse(is.na(data$X3[which(data$X1=='120Sn')]),0,1),
  "COWG_120Sn" = ifelse(is.na(data$X5[which(data$X1=='120Sn')]),0,1),
  "GAL_120Sn" = ifelse(is.na(data$X6[which(data$X1=='120Sn')]),0,1),
  "Confluence_120Sn" = ifelse(is.na(data$X7[which(data$X1=='120Sn')]),0,1),
  "Amous_120Sn" = ifelse(is.na(data$X8[which(data$X1=='120Sn')]),0,1),
  "S1_118Sn" = ifelse(is.na(data$X4[which(data$X1=='118Sn')]),0,1),
  "S5_118Sn" = ifelse(is.na(data$X3[which(data$X1=='118Sn')]),0,1),
  "COWG_118Sn" = ifelse(is.na(data$X5[which(data$X1=='118Sn')]),0,1),
  "GAL_118Sn" = ifelse(is.na(data$X6[which(data$X1=='118Sn')]),0,1),
  "Confluence_118Sn" = ifelse(is.na(data$X7[which(data$X1=='118Sn')]),0,1),
  "Amous_118Sn" = ifelse(is.na(data$X8[which(data$X1=='118Sn')]),0,1)
) %>%
  arrange(dates)
```

```{r}
strontium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='88Sr')]), data$X4[which(data$X1=='86Sr')], data$X4[which(data$X1=='88Sr')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='88Sr')]), data$X3[which(data$X1=='86Sr')], data$X3[which(data$X1=='88Sr')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='88Sr')]), data$X5[which(data$X1=='86Sr')], data$X5[which(data$X1=='88Sr')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='88Sr')]), data$X6[which(data$X1=='86Sr')], data$X6[which(data$X1=='88Sr')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='88Sr')]), data$X7[which(data$X1=='86Sr')], data$X4[which(data$X7=='88Sr')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='88Sr')]), data$X8[which(data$X1=='86Sr')], data$X8[which(data$X1=='88Sr')]),
  "S1_88Sr" = ifelse(is.na(data$X4[which(data$X1=='88Sr')]),0,1),
  "S5_88Sr" = ifelse(is.na(data$X3[which(data$X1=='88Sr')]),0,1),
  "COWG_88Sr" = ifelse(is.na(data$X5[which(data$X1=='88Sr')]),0,1),
  "GAL_88Sr" = ifelse(is.na(data$X6[which(data$X1=='88Sr')]),0,1),
  "Confluence_88Sr" = ifelse(is.na(data$X7[which(data$X1=='88Sr')]),0,1),
  "Amous_88Sr" = ifelse(is.na(data$X8[which(data$X1=='88Sr')]),0,1),
  "S1_86Sr" = ifelse(is.na(data$X4[which(data$X1=='86Sr')]),0,1),
  "S5_86Sr" = ifelse(is.na(data$X3[which(data$X1=='86Sr')]),0,1),
  "COWG_86Sr" = ifelse(is.na(data$X5[which(data$X1=='86Sr')]),0,1),
  "GAL_86Sr" = ifelse(is.na(data$X6[which(data$X1=='86Sr')]),0,1),
  "Confluence_86Sr" = ifelse(is.na(data$X7[which(data$X1=='86Sr')]),0,1),
  "Amous_86Sr" = ifelse(is.na(data$X8[which(data$X1=='86Sr')]),0,1)
) %>%
  arrange(dates)
```

```{r}
nickel <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='62Ni')]), data$X4[which(data$X1=='60Ni')], data$X4[which(data$X1=='62Ni')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='62Ni')]), data$X3[which(data$X1=='60Ni')], data$X3[which(data$X1=='62Ni')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='62Ni')]), data$X5[which(data$X1=='60Ni')], data$X5[which(data$X1=='62Ni')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='62Ni')]), data$X6[which(data$X1=='60Ni')], data$X6[which(data$X1=='62Ni')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='62Ni')]), data$X7[which(data$X1=='60Ni')], data$X4[which(data$X7=='62Ni')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='62Ni')]), data$X8[which(data$X1=='60Ni')], data$X8[which(data$X1=='62Ni')]),
  "S1_62Ni" = ifelse(is.na(data$X4[which(data$X1=='62Ni')]),0,1),
  "S5_62Ni" = ifelse(is.na(data$X3[which(data$X1=='62Ni')]),0,1),
  "COWG_62Ni" = ifelse(is.na(data$X5[which(data$X1=='62Ni')]),0,1),
  "GAL_62Ni" = ifelse(is.na(data$X6[which(data$X1=='62Ni')]),0,1),
  "Confluence_62Ni" = ifelse(is.na(data$X7[which(data$X1=='62Ni')]),0,1),
  "Amous_62Ni" = ifelse(is.na(data$X8[which(data$X1=='62Ni')]),0,1),
  "S1_60Ni" = ifelse(is.na(data$X4[which(data$X1=='60Ni')]),0,1),
  "S5_60Ni" = ifelse(is.na(data$X3[which(data$X1=='60Ni')]),0,1),
  "COWG_60Ni" = ifelse(is.na(data$X5[which(data$X1=='60Ni')]),0,1),
  "GAL_60Ni" = ifelse(is.na(data$X6[which(data$X1=='60Ni')]),0,1),
  "Confluence_60Ni" = ifelse(is.na(data$X7[which(data$X1=='60Ni')]),0,1),
  "Amous_60Ni" = ifelse(is.na(data$X8[which(data$X1=='60Ni')]),0,1)
) %>%
  arrange(dates)
```

```{r}
zinc <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='68Zn')]), ifelse(is.na(data$X4[which(data$X1=='67Zn')]), data$X4[which(data$X1=='66Zn')], data$X4[which(data$X1=='67Zn')]), data$X4[which(data$X1=='68Zn')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='68Zn')]), ifelse(is.na(data$X3[which(data$X1=='67Zn')]), data$X3[which(data$X1=='66Zn')], data$X3[which(data$X1=='67Zn')]), data$X3[which(data$X1=='68Zn')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='68Zn')]), ifelse(is.na(data$X5[which(data$X1=='67Zn')]), data$X5[which(data$X1=='66Zn')], data$X5[which(data$X1=='67Zn')]), data$X5[which(data$X1=='68Zn')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='68Zn')]), ifelse(is.na(data$X6[which(data$X1=='67Zn')]), data$X6[which(data$X1=='66Zn')], data$X6[which(data$X1=='67Zn')]), data$X6[which(data$X1=='68Zn')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='68Zn')]), ifelse(is.na(data$X7[which(data$X1=='67Zn')]), data$X7[which(data$X1=='66Zn')], data$X7[which(data$X1=='67Zn')]), data$X7[which(data$X1=='68Zn')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='68Zn')]), ifelse(is.na(data$X8[which(data$X1=='67Zn')]), data$X8[which(data$X1=='66Zn')], data$X8[which(data$X1=='67Zn')]), data$X8[which(data$X1=='68Zn')]),
  "S1_68Zn" = ifelse(is.na(data$X4[which(data$X1=='68Zn')]),0,1),
  "S5_68Zn" = ifelse(is.na(data$X3[which(data$X1=='68Zn')]),0,1),
  "COWG_68Zn" = ifelse(is.na(data$X5[which(data$X1=='68Zn')]),0,1),
  "GAL_68Zn" = ifelse(is.na(data$X6[which(data$X1=='68Zn')]),0,1),
  "Confluence_68Zn" = ifelse(is.na(data$X7[which(data$X1=='68Zn')]),0,1),
  "Amous_68Zn" = ifelse(is.na(data$X8[which(data$X1=='68Zn')]),0,1),
  "S1_67Zn" = ifelse(is.na(data$X4[which(data$X1=='67Zn')]),0,1),
  "S5_67Zn" = ifelse(is.na(data$X3[which(data$X1=='67Zn')]),0,1),
  "COWG_67Zn" = ifelse(is.na(data$X5[which(data$X1=='67Zn')]),0,1),
  "GAL_67Zn" = ifelse(is.na(data$X6[which(data$X1=='67Zn')]),0,1),
  "Confluence_67Zn" = ifelse(is.na(data$X7[which(data$X1=='67Zn')]),0,1),
  "Amous_67Zn" = ifelse(is.na(data$X8[which(data$X1=='67Zn')]),0,1),
  "S1_66Zn" = ifelse(is.na(data$X4[which(data$X1=='66Zn')]),0,1),
  "S5_66Zn" = ifelse(is.na(data$X3[which(data$X1=='66Zn')]),0,1),
  "COWG_66Zn" = ifelse(is.na(data$X5[which(data$X1=='66Zn')]),0,1),
  "GAL_66Zn" = ifelse(is.na(data$X6[which(data$X1=='66Zn')]),0,1),
  "Confluence_66Zn" = ifelse(is.na(data$X7[which(data$X1=='66Zn')]),0,1),
  "Amous_66Zn" = ifelse(is.na(data$X8[which(data$X1=='66Zn')]),0,1)
) %>%
  arrange(dates)
```

```{r}
cadmium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='114Cd')]), data$X4[which(data$X1=='111Cd')], data$X4[which(data$X1=='114Cd')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='114Cd')]), data$X3[which(data$X1=='111Cd')], data$X3[which(data$X1=='114Cd')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='114Cd')]), data$X5[which(data$X1=='111Cd')], data$X5[which(data$X1=='114Cd')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='114Cd')]), data$X6[which(data$X1=='111Cd')], data$X6[which(data$X1=='114Cd')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='114Cd')]), data$X7[which(data$X1=='111Cd')], data$X4[which(data$X7=='114Cd')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='114Cd')]), data$X8[which(data$X1=='111Cd')], data$X8[which(data$X1=='114Cd')]),
  "S1_114Cd" = ifelse(is.na(data$X4[which(data$X1=='114Cd')]),0,1),
  "S5_114Cd" = ifelse(is.na(data$X3[which(data$X1=='114Cd')]),0,1),
  "COWG_114Cd" = ifelse(is.na(data$X5[which(data$X1=='114Cd')]),0,1),
  "GAL_114Cd" = ifelse(is.na(data$X6[which(data$X1=='114Cd')]),0,1),
  "Confluence_114Cd" = ifelse(is.na(data$X7[which(data$X1=='114Cd')]),0,1),
  "Amous_114Cd" = ifelse(is.na(data$X8[which(data$X1=='114Cd')]),0,1),
  "S1_111Cd" = ifelse(is.na(data$X4[which(data$X1=='111Cd')]),0,1),
  "S5_111Cd" = ifelse(is.na(data$X3[which(data$X1=='111Cd')]),0,1),
  "COWG_111Cd" = ifelse(is.na(data$X5[which(data$X1=='111Cd')]),0,1),
  "GAL_111Cd" = ifelse(is.na(data$X6[which(data$X1=='111Cd')]),0,1),
  "Confluence_111Cd" = ifelse(is.na(data$X7[which(data$X1=='111Cd')]),0,1),
  "Amous_111Cd" = ifelse(is.na(data$X8[which(data$X1=='111Cd')]),0,1)
) %>%
  arrange(dates)
```

```{r}
antimony <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='123Sb')]), data$X4[which(data$X1=='121Sb')], data$X4[which(data$X1=='123Sb')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='123Sb')]), data$X3[which(data$X1=='121Sb')], data$X3[which(data$X1=='123Sb')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='123Sb')]), data$X5[which(data$X1=='121Sb')], data$X5[which(data$X1=='123Sb')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='123Sb')]), data$X6[which(data$X1=='121Sb')], data$X6[which(data$X1=='123Sb')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='123Sb')]), data$X7[which(data$X1=='121Sb')], data$X4[which(data$X7=='123Sb')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='123Sb')]), data$X8[which(data$X1=='121Sb')], data$X8[which(data$X1=='123Sb')]),
  "S1_123Sb" = ifelse(is.na(data$X4[which(data$X1=='123Sb')]),0,1),
  "S5_123Sb" = ifelse(is.na(data$X3[which(data$X1=='123Sb')]),0,1),
  "COWG_123Sb" = ifelse(is.na(data$X5[which(data$X1=='123Sb')]),0,1),
  "GAL_123Sb" = ifelse(is.na(data$X6[which(data$X1=='123Sb')]),0,1),
  "Confluence_123Sb" = ifelse(is.na(data$X7[which(data$X1=='123Sb')]),0,1),
  "Amous_123Sb" = ifelse(is.na(data$X8[which(data$X1=='123Sb')]),0,1),
  "S1_121Sb" = ifelse(is.na(data$X4[which(data$X1=='121Sb')]),0,1),
  "S5_121Sb" = ifelse(is.na(data$X3[which(data$X1=='121Sb')]),0,1),
  "COWG_121Sb" = ifelse(is.na(data$X5[which(data$X1=='121Sb')]),0,1),
  "GAL_121Sb" = ifelse(is.na(data$X6[which(data$X1=='121Sb')]),0,1),
  "Confluence_121Sb" = ifelse(is.na(data$X7[which(data$X1=='121Sb')]),0,1),
  "Amous_121Sb" = ifelse(is.na(data$X8[which(data$X1=='121Sb')]),0,1)
) %>%
  arrange(dates)
```

```{r}
thallium <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='205Tl')]), data$X4[which(data$X1=='203Tl')], data$X4[which(data$X1=='205Tl')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='205Tl')]), data$X3[which(data$X1=='203Tl')], data$X3[which(data$X1=='205Tl')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='205Tl')]), data$X5[which(data$X1=='203Tl')], data$X5[which(data$X1=='205Tl')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='205Tl')]), data$X6[which(data$X1=='203Tl')], data$X6[which(data$X1=='205Tl')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='205Tl')]), data$X7[which(data$X1=='203Tl')], data$X4[which(data$X7=='205Tl')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='205Tl')]), data$X8[which(data$X1=='203Tl')], data$X8[which(data$X1=='205Tl')]),
  "S1_205Tl" = ifelse(is.na(data$X4[which(data$X1=='205Tl')]),0,1),
  "S5_205Tl" = ifelse(is.na(data$X3[which(data$X1=='205Tl')]),0,1),
  "COWG_205Tl" = ifelse(is.na(data$X5[which(data$X1=='205Tl')]),0,1),
  "GAL_205Tl" = ifelse(is.na(data$X6[which(data$X1=='205Tl')]),0,1),
  "Confluence_205Tl" = ifelse(is.na(data$X7[which(data$X1=='205Tl')]),0,1),
  "Amous_205Tl" = ifelse(is.na(data$X8[which(data$X1=='205Tl')]),0,1),
  "S1_203Tl" = ifelse(is.na(data$X4[which(data$X1=='203Tl')]),0,1),
  "S5_203Tl" = ifelse(is.na(data$X3[which(data$X1=='203Tl')]),0,1),
  "COWG_203Tl" = ifelse(is.na(data$X5[which(data$X1=='203Tl')]),0,1),
  "GAL_203Tl" = ifelse(is.na(data$X6[which(data$X1=='203Tl')]),0,1),
  "Confluence_203Tl" = ifelse(is.na(data$X7[which(data$X1=='203Tl')]),0,1),
  "Amous_203Tl" = ifelse(is.na(data$X8[which(data$X1=='203Tl')]),0,1)
) %>%
  arrange(dates)
```

```{r}
lead <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='208Pb')]), ifelse(is.na(data$X4[which(data$X1=='207Pb')]), data$X4[which(data$X1=='206Pb')], data$X4[which(data$X1=='207Pb')]), data$X4[which(data$X1=='208Pb')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='208Pb')]), ifelse(is.na(data$X3[which(data$X1=='207Pb')]), data$X3[which(data$X1=='206Pb')], data$X3[which(data$X1=='207Pb')]), data$X3[which(data$X1=='208Pb')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='208Pb')]), ifelse(is.na(data$X5[which(data$X1=='207Pb')]), data$X5[which(data$X1=='206Pb')], data$X5[which(data$X1=='207Pb')]), data$X5[which(data$X1=='208Pb')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='208Pb')]), ifelse(is.na(data$X6[which(data$X1=='207Pb')]), data$X6[which(data$X1=='206Pb')], data$X6[which(data$X1=='207Pb')]), data$X6[which(data$X1=='208Pb')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='208Pb')]), ifelse(is.na(data$X7[which(data$X1=='207Pb')]), data$X7[which(data$X1=='206Pb')], data$X7[which(data$X1=='207Pb')]), data$X7[which(data$X1=='208Pb')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='208Pb')]), ifelse(is.na(data$X8[which(data$X1=='207Pb')]), data$X8[which(data$X1=='206Pb')], data$X8[which(data$X1=='207Pb')]), data$X8[which(data$X1=='208Pb')]),
  "S1_208Pb" = ifelse(is.na(data$X4[which(data$X1=='208Pb')]),0,1),
  "S5_208Pb" = ifelse(is.na(data$X3[which(data$X1=='208Pb')]),0,1),
  "COWG_208Pb" = ifelse(is.na(data$X5[which(data$X1=='208Pb')]),0,1),
  "GAL_208Pb" = ifelse(is.na(data$X6[which(data$X1=='208Pb')]),0,1),
  "Confluence_208Pb" = ifelse(is.na(data$X7[which(data$X1=='208Pb')]),0,1),
  "Amous_208Pb" = ifelse(is.na(data$X8[which(data$X1=='208Pb')]),0,1),
  "S1_207Pb" = ifelse(is.na(data$X4[which(data$X1=='207Pb')]),0,1),
  "S5_207Pb" = ifelse(is.na(data$X3[which(data$X1=='207Pb')]),0,1),
  "COWG_207Pb" = ifelse(is.na(data$X5[which(data$X1=='207Pb')]),0,1),
  "GAL_207Pb" = ifelse(is.na(data$X6[which(data$X1=='207Pb')]),0,1),
  "Confluence_207Pb" = ifelse(is.na(data$X7[which(data$X1=='207Pb')]),0,1),
  "Amous_207Pb" = ifelse(is.na(data$X8[which(data$X1=='207Pb')]),0,1),
  "S1_206Pb" = ifelse(is.na(data$X4[which(data$X1=='206Pb')]),0,1),
  "S5_206Pb" = ifelse(is.na(data$X3[which(data$X1=='206Pb')]),0,1),
  "COWG_206Pb" = ifelse(is.na(data$X5[which(data$X1=='206Pb')]),0,1),
  "GAL_206Pb" = ifelse(is.na(data$X6[which(data$X1=='206Pb')]),0,1),
  "Confluence_206Pb" = ifelse(is.na(data$X7[which(data$X1=='206Pb')]),0,1),
  "Amous_206Pb" = ifelse(is.na(data$X8[which(data$X1=='206Pb')]),0,1)
) %>%
  arrange(dates)
```

```{r}
lanthanum <- data.frame(
  "dates" = dates,
  "S1" = data$X4[which(data$X1=='139La')],
  "S5" = data$X3[which(data$X1=='139La')],
  "COWG" = data$X5[which(data$X1=='139La')],
  "GAL" = data$X6[which(data$X1=='139La')],
  "Confluence" = data$X7[which(data$X1=='139La')],
  "Amous" = data$X8[which(data$X1=='139La')]
) %>%
  arrange(dates)
```

```{r}
baryum <- data.frame(
  "dates" = dates,
  "S1" = ifelse(is.na(data$X4[which(data$X1=='138Ba')]), ifelse(is.na(data$X4[which(data$X1=='137Ba')]), data$X4[which(data$X1=='136Ba')], data$X4[which(data$X1=='137Ba')]), data$X4[which(data$X1=='138Ba')]),
  "S5" = ifelse(is.na(data$X3[which(data$X1=='138Ba')]), ifelse(is.na(data$X3[which(data$X1=='137Ba')]), data$X3[which(data$X1=='136Ba')], data$X3[which(data$X1=='137Ba')]), data$X3[which(data$X1=='138Ba')]),
  "COWG" = ifelse(is.na(data$X5[which(data$X1=='138Ba')]), ifelse(is.na(data$X5[which(data$X1=='137Ba')]), data$X5[which(data$X1=='136Ba')], data$X5[which(data$X1=='137Ba')]), data$X5[which(data$X1=='138Ba')]),
  "GAL" = ifelse(is.na(data$X6[which(data$X1=='138Ba')]), ifelse(is.na(data$X6[which(data$X1=='137Ba')]), data$X6[which(data$X1=='136Ba')], data$X6[which(data$X1=='137Ba')]), data$X6[which(data$X1=='138Ba')]),
  "Confluence" = ifelse(is.na(data$X7[which(data$X1=='138Ba')]), ifelse(is.na(data$X7[which(data$X1=='137Ba')]), data$X7[which(data$X1=='136Ba')], data$X7[which(data$X1=='137Ba')]), data$X7[which(data$X1=='138Ba')]),
  "Amous" = ifelse(is.na(data$X8[which(data$X1=='138Ba')]), ifelse(is.na(data$X8[which(data$X1=='137Ba')]), data$X8[which(data$X1=='136Ba')], data$X8[which(data$X1=='137Ba')]), data$X8[which(data$X1=='138Ba')]),
  "S1_138Ba" = ifelse(is.na(data$X4[which(data$X1=='138Ba')]),0,1),
  "S5_138Ba" = ifelse(is.na(data$X3[which(data$X1=='138Ba')]),0,1),
  "COWG_138Ba" = ifelse(is.na(data$X5[which(data$X1=='138Ba')]),0,1),
  "GAL_138Ba" = ifelse(is.na(data$X6[which(data$X1=='138Ba')]),0,1),
  "Confluence_138Ba" = ifelse(is.na(data$X7[which(data$X1=='138Ba')]),0,1),
  "Amous_138Ba" = ifelse(is.na(data$X8[which(data$X1=='138Ba')]),0,1),
  "S1_137Ba" = ifelse(is.na(data$X4[which(data$X1=='137Ba')]),0,1),
  "S5_137Ba" = ifelse(is.na(data$X3[which(data$X1=='137Ba')]),0,1),
  "COWG_137Ba" = ifelse(is.na(data$X5[which(data$X1=='137Ba')]),0,1),
  "GAL_137Ba" = ifelse(is.na(data$X6[which(data$X1=='137Ba')]),0,1),
  "Confluence_137Ba" = ifelse(is.na(data$X7[which(data$X1=='137Ba')]),0,1),
  "Amous_137Ba" = ifelse(is.na(data$X8[which(data$X1=='137Ba')]),0,1),
  "S1_136Ba" = ifelse(is.na(data$X4[which(data$X1=='136Ba')]),0,1),
  "S5_136Ba" = ifelse(is.na(data$X3[which(data$X1=='136Ba')]),0,1),
  "COWG_136Ba" = ifelse(is.na(data$X5[which(data$X1=='136Ba')]),0,1),
  "GAL_136Ba" = ifelse(is.na(data$X6[which(data$X1=='136Ba')]),0,1),
  "Confluence_136Ba" = ifelse(is.na(data$X7[which(data$X1=='136Ba')]),0,1),
  "Amous_136Ba" = ifelse(is.na(data$X8[which(data$X1=='136Ba')]),0,1)
) %>%
  arrange(dates)
```

# Creating and saving a data.frame for each station

```{r}
Source_S1 <- data.frame(
  dates = temperature$dates,
  temperature = temperature$S1,
  ph = ph$S1,
  eh = eh$S1,
  o2 = o2$S1,
  o2_HACH = o2$S1_hach,
  o2_colorimétrie = o2$S1_colorimetrie,
  o2_Mettler = o2$S1_mettler,
  conductivity = conductivity$S1,
  aluminium = aluminium$S1,
  antimony = antimony$S1,
  antimony_123Sb = antimony$S1_123Sb,
  antimony_121Sb = antimony$S1_121Sb,
  asV = asV$S1,
  asIII = asIII$S1,
  total_arsenic = total_arsenic$S1,
  baryum = baryum$S1,
  baryum_138Ba = baryum$S1_138Ba,
  baryum_137Ba = baryum$S1_137Ba,
  baryum_136Ba = baryum$S1_136Ba,
  bore = bore$S1,
  cadmium = cadmium$S1,
  cadmium_114Cd = cadmium$S1_114Cd,
  cadmium_111Cd = cadmium$S1_111Cd,
  calcium = calcium$S1,
  calcium_44Ca = calcium$S1_44Ca,
  calcium_43Ca = calcium$S1_43Ca,
  caesium = caesium$S1,
  chromium = chromium$S1,
  chromium_53Cr = chromium$S1_53Cr,
  chromium_52Cr = chromium$S1_52Cr,
  cobalt = cobalt$S1,
  copper = copper$S1,
  copper_65Cu = copper$S1_65Cu,
  copper_63Cu = copper$S1_63Cu,
  tin = tin$S1,
  tin_120Sn = tin$S1_120Sn,
  tin_118Sn = tin$S1_118Sn,
  total_iron = total_iron$S1,
  lanthanum = lanthanum$S1,
  magnesium = magnesium$S1,
  molybdenum = molybdenum$S1,
  molybdenum_97Mo = molybdenum$S1_97Mo,
  molybdenum_95Mo = molybdenum$S1_95Mo,
  nickel = nickel$S1,
  nickel_62Ni = nickel$S1_62Ni,
  nickel_60Ni = nickel$S1_60Ni,
  nitrate = nitrate$S1,
  lead = lead$S1,
  lead_208Pb = lead$S1_208Pb,
  lead_207Pb = lead$S1_207Pb,
  lead_206Pb = lead$S1_206Pb,
  rubidium = rubidium$S1,
  sodium = sodium$S1,
  sulfur = sulfur$S1,
  strontium = strontium$S1,
  strontium_88Sr = strontium$S1_88Sr,
  strontium_86Sr = strontium$S1_86Sr,
  sulfate = sulfate$S1,
  thallium = thallium$S1,
  thallium_205Tl = thallium$S1_205Tl,
  thallium_203Tl = thallium$S1_203Tl,
  titanium = titanium$S1,
  titanium_49Ti = titanium$S1_49Ti,
  titanium_47Ti = titanium$S1_47Ti,
  vanadium = vanadium$S1,
  yttrium = yttrium$S1,
  zinc = zinc$S1,
  zinc_68Zn = zinc$S1_68Zn,
  zinc_67Zn = zinc$S1_67Zn,
  zinc_66Zn = zinc$S1_66Zn,
  zirconium = zirconium$S1,
  bromide = bromide$S1,
  calcium_ion = calcium_ion$S1,
  feII = feII$S1,
  fluoride = fluoride$S1,
  magnesium_ion = magnesium_ion$S1,
  potassium_ion = potassium_ion$S1,
  sodium_ion = sodium_ion$S1
)
```

```{r}
S5 <- data.frame(
  dates = temperature$dates,
  temperature = temperature$S5,
  ph = ph$S5,
  eh = eh$S5,
  o2 = o2$S5,
  o2_HACH = o2$S5_hach,
  o2_colorimétrie = o2$S5_colorimetrie,
  o2_Mettler = o2$S5_mettler,
  conductivity = conductivity$S5,
  aluminium = aluminium$S5,
  antimony = antimony$S5,
  antimony_123Sb = antimony$S5_123Sb,
  antimony_121Sb = antimony$S5_121Sb,
  asV = asV$S5,
  asIII = asIII$S5,
  total_arsenic = total_arsenic$S5,
  baryum = baryum$S5,
  baryum_138Ba = baryum$S5_138Ba,
  baryum_137Ba = baryum$S5_137Ba,
  baryum_136Ba = baryum$S5_136Ba,
  bore = bore$S5,
  cadmium = cadmium$S5,
  cadmium_114Cd = cadmium$S5_114Cd,
  cadmium_111Cd = cadmium$S5_111Cd,
  calcium = calcium$S5,
  calcium_44Ca = calcium$S5_44Ca,
  calcium_43Ca = calcium$S5_43Ca,
  caesium = caesium$S5,
  chromium = chromium$S5,
  chromium_53Cr = chromium$S5_53Cr,
  chromium_52Cr = chromium$S5_52Cr,
  cobalt = cobalt$S5,
  copper = copper$S5,
  copper_65Cu = copper$S5_65Cu,
  copper_63Cu = copper$S5_63Cu,
  tin = tin$S5,
  tin_120Sn = tin$S5_120Sn,
  tin_118Sn = tin$S5_118Sn,
  total_iron = total_iron$S5,
  lanthanum = lanthanum$S5,
  magnesium = magnesium$S5,
  molybdenum = molybdenum$S5,
  molybdenum_97Mo = molybdenum$S5_97Mo,
  molybdenum_95Mo = molybdenum$S5_95Mo,
  nickel = nickel$S5,
  nickel_62Ni = nickel$S5_62Ni,
  nickel_60Ni = nickel$S5_60Ni,
  nitrate = nitrate$S5,
  lead = lead$S5,
  lead_208Pb = lead$S5_208Pb,
  lead_207Pb = lead$S5_207Pb,
  lead_206Pb = lead$S5_206Pb,
  rubidium = rubidium$S5,
  sodium = sodium$S5,
  sulfur = sulfur$S5,
  strontium = strontium$S5,
  strontium_88Sr = strontium$S5_88Sr,
  strontium_86Sr = strontium$S5_86Sr,
  sulfate = sulfate$S5,
  thallium = thallium$S5,
  thallium_205Tl = thallium$S5_205Tl,
  thallium_203Tl = thallium$S5_203Tl,
  titanium = titanium$S5,
  titanium_49Ti = titanium$S5_49Ti,
  titanium_47Ti = titanium$S5_47Ti,
  vanadium = vanadium$S5,
  yttrium = yttrium$S5,
  zinc = zinc$S5,
  zinc_68Zn = zinc$S5_68Zn,
  zinc_67Zn = zinc$S5_67Zn,
  zinc_66Zn = zinc$S5_66Zn,
  zirconium = zirconium$S5,
  bromide = bromide$S5,
  calcium_ion = calcium_ion$S5,
  feII = feII$S5,
  fluoride = fluoride$S5,
  magnesium_ion = magnesium_ion$S5,
  potassium_ion = potassium_ion$S5,
  sodium_ion = sodium_ion$S5
)
```

```{r}
COWG <- data.frame(
  dates = temperature$dates,
  temperature = temperature$COWG,
  ph = ph$COWG,
  eh = eh$COWG,
  o2 = o2$COWG,
  o2_HACH = o2$COWG_hach,
  o2_colorimétrie = o2$COWG_colorimetrie,
  o2_Mettler = o2$COWG_mettler,
  conductivity = conductivity$COWG,
  aluminium = aluminium$COWG,
  antimony = antimony$COWG,
  antimony_123Sb = antimony$COWG_123Sb,
  antimony_121Sb = antimony$COWG_121Sb,
  asV = asV$COWG,
  asIII = asIII$COWG,
  total_arsenic = total_arsenic$COWG,
  baryum = baryum$COWG,
  baryum_138Ba = baryum$COWG_138Ba,
  baryum_137Ba = baryum$COWG_137Ba,
  baryum_136Ba = baryum$COWG_136Ba,
  bore = bore$COWG,
  cadmium = cadmium$COWG,
  cadmium_114Cd = cadmium$COWG_114Cd,
  cadmium_111Cd = cadmium$COWG_111Cd,
  calcium = calcium$COWG,
  calcium_44Ca = calcium$COWG_44Ca,
  calcium_43Ca = calcium$COWG_43Ca,
  caesium = caesium$COWG,
  chromium = chromium$COWG,
  chromium_53Cr = chromium$COWG_53Cr,
  chromium_52Cr = chromium$COWG_52Cr,
  cobalt = cobalt$COWG,
  copper = copper$COWG,
  copper_65Cu = copper$COWG_65Cu,
  copper_63Cu = copper$COWG_63Cu,
  tin = tin$COWG,
  tin_120Sn = tin$COWG_120Sn,
  tin_118Sn = tin$COWG_118Sn,
  total_iron = total_iron$COWG,
  lanthanum = lanthanum$COWG,
  magnesium = magnesium$COWG,
  molybdenum = molybdenum$COWG,
  molybdenum_97Mo = molybdenum$COWG_97Mo,
  molybdenum_95Mo = molybdenum$COWG_95Mo,
  nickel = nickel$COWG,
  nickel_62Ni = nickel$COWG_62Ni,
  nickel_60Ni = nickel$COWG_60Ni,
  nitrate = nitrate$COWG,
  lead = lead$COWG,
  lead_208Pb = lead$COWG_208Pb,
  lead_207Pb = lead$COWG_207Pb,
  lead_206Pb = lead$COWG_206Pb,
  rubidium = rubidium$COWG,
  sodium = sodium$COWG,
  sulfur = sulfur$COWG,
  strontium = strontium$COWG,
  strontium_88Sr = strontium$COWG_88Sr,
  strontium_86Sr = strontium$COWG_86Sr,
  sulfate = sulfate$COWG,
  thallium = thallium$COWG,
  thallium_205Tl = thallium$COWG_205Tl,
  thallium_203Tl = thallium$COWG_203Tl,
  titanium = titanium$COWG,
  titanium_49Ti = titanium$COWG_49Ti,
  titanium_47Ti = titanium$COWG_47Ti,
  vanadium = vanadium$COWG,
  yttrium = yttrium$COWG,
  zinc = zinc$COWG,
  zinc_68Zn = zinc$COWG_68Zn,
  zinc_67Zn = zinc$COWG_67Zn,
  zinc_66Zn = zinc$COWG_66Zn,
  zirconium = zirconium$COWG,
  bromide = bromide$COWG,
  calcium_ion = calcium_ion$COWG,
  feII = feII$COWG,
  fluoride = fluoride$COWG,
  magnesium_ion = magnesium_ion$COWG,
  potassium_ion = potassium_ion$COWG,
  sodium_ion = sodium_ion$COWG
)
```

```{r}
GAL <- data.frame(
  dates = temperature$dates,
  temperature = temperature$GAL,
  ph = ph$GAL,
  eh = eh$GAL,
  o2 = o2$GAL,
  o2_HACH = o2$GAL_hach,
  o2_colorimétrie = o2$GAL_colorimetrie,
  o2_Mettler = o2$GAL_mettler,
  conductivity = conductivity$GAL,
  aluminium = aluminium$GAL,
  antimony = antimony$GAL,
  antimony_123Sb = antimony$GAL_123Sb,
  antimony_121Sb = antimony$GAL_121Sb,
  asV = asV$GAL,
  asIII = asIII$GAL,
  total_arsenic = total_arsenic$GAL,
  baryum = baryum$GAL,
  baryum_138Ba = baryum$GAL_138Ba,
  baryum_137Ba = baryum$GAL_137Ba,
  baryum_136Ba = baryum$GAL_136Ba,
  bore = bore$GAL,
  cadmium = cadmium$GAL,
  cadmium_114Cd = cadmium$GAL_114Cd,
  cadmium_111Cd = cadmium$GAL_111Cd,
  calcium = calcium$GAL,
  calcium_44Ca = calcium$GAL_44Ca,
  calcium_43Ca = calcium$GAL_43Ca,
  caesium = caesium$GAL,
  chromium = chromium$GAL,
  chromium_53Cr = chromium$GAL_53Cr,
  chromium_52Cr = chromium$GAL_52Cr,
  cobalt = cobalt$GAL,
  copper = copper$GAL,
  copper_65Cu = copper$GAL_65Cu,
  copper_63Cu = copper$GAL_63Cu,
  tin = tin$GAL,
  tin_120Sn = tin$GAL_120Sn,
  tin_118Sn = tin$GAL_118Sn,
  total_iron = total_iron$GAL,
  lanthanum = lanthanum$GAL,
  magnesium = magnesium$GAL,
  molybdenum = molybdenum$GAL,
  molybdenum_97Mo = molybdenum$GAL_97Mo,
  molybdenum_95Mo = molybdenum$GAL_95Mo,
  nickel = nickel$GAL,
  nickel_62Ni = nickel$GAL_62Ni,
  nickel_60Ni = nickel$GAL_60Ni,
  nitrate = nitrate$GAL,
  lead = lead$GAL,
  lead_208Pb = lead$GAL_208Pb,
  lead_207Pb = lead$GAL_207Pb,
  lead_206Pb = lead$GAL_206Pb,
  rubidium = rubidium$GAL,
  sodium = sodium$GAL,
  sulfur = sulfur$GAL,
  strontium = strontium$GAL,
  strontium_88Sr = strontium$GAL_88Sr,
  strontium_86Sr = strontium$GAL_86Sr,
  sulfate = sulfate$GAL,
  thallium = thallium$GAL,
  thallium_205Tl = thallium$GAL_205Tl,
  thallium_203Tl = thallium$GAL_203Tl,
  titanium = titanium$GAL,
  titanium_49Ti = titanium$GAL_49Ti,
  titanium_47Ti = titanium$GAL_47Ti,
  vanadium = vanadium$GAL,
  yttrium = yttrium$GAL,
  zinc = zinc$GAL,
  zinc_68Zn = zinc$GAL_68Zn,
  zinc_67Zn = zinc$GAL_67Zn,
  zinc_66Zn = zinc$GAL_66Zn,
  zirconium = zirconium$GAL,
  bromide = bromide$GAL,
  calcium_ion = calcium_ion$GAL,
  feII = feII$GAL,
  fluoride = fluoride$GAL,
  magnesium_ion = magnesium_ion$GAL,
  potassium_ion = potassium_ion$GAL,
  sodium_ion = sodium_ion$GAL
)
```

```{r}
Confluence <- data.frame(
  dates = temperature$dates,
  temperature = temperature$Confluence,
  ph = ph$Confluence,
  eh = eh$Confluence,
  o2 = o2$Confluence,
  o2_HACH = o2$Confluence_hach,
  o2_colorimétrie = o2$Confluence_colorimetrie,
  o2_Mettler = o2$Confluence_mettler,
  conductivity = conductivity$Confluence,
  aluminium = aluminium$Confluence,
  antimony = antimony$Confluence,
  antimony_123Sb = antimony$Confluence_123Sb,
  antimony_121Sb = antimony$Confluence_121Sb,
  asV = asV$Confluence,
  asIII = asIII$Confluence,
  total_arsenic = total_arsenic$Confluence,
  baryum = baryum$Confluence,
  baryum_138Ba = baryum$Confluence_138Ba,
  baryum_137Ba = baryum$Confluence_137Ba,
  baryum_136Ba = baryum$Confluence_136Ba,
  bore = bore$Confluence,
  cadmium = cadmium$Confluence,
  cadmium_114Cd = cadmium$Confluence_114Cd,
  cadmium_111Cd = cadmium$Confluence_111Cd,
  calcium = calcium$Confluence,
  calcium_44Ca = calcium$Confluence_44Ca,
  calcium_43Ca = calcium$Confluence_43Ca,
  caesium = caesium$Confluence,
  chromium = chromium$Confluence,
  chromium_53Cr = chromium$Confluence_53Cr,
  chromium_52Cr = chromium$Confluence_52Cr,
  cobalt = cobalt$Confluence,
  copper = copper$Confluence,
  copper_65Cu = copper$Confluence_65Cu,
  copper_63Cu = copper$Confluence_63Cu,
  tin = tin$Confluence,
  tin_120Sn = tin$Confluence_120Sn,
  tin_118Sn = tin$Confluence_118Sn,
  total_iron = total_iron$Confluence,
  lanthanum = lanthanum$Confluence,
  magnesium = magnesium$Confluence,
  molybdenum = molybdenum$Confluence,
  molybdenum_97Mo = molybdenum$Confluence_97Mo,
  molybdenum_95Mo = molybdenum$Confluence_95Mo,
  nickel = nickel$Confluence,
  nickel_62Ni = nickel$Confluence_62Ni,
  nickel_60Ni = nickel$Confluence_60Ni,
  nitrate = nitrate$Confluence,
  lead = lead$Confluence,
  lead_208Pb = lead$Confluence_208Pb,
  lead_207Pb = lead$Confluence_207Pb,
  lead_206Pb = lead$Confluence_206Pb,
  rubidium = rubidium$Confluence,
  sodium = sodium$Confluence,
  sulfur = sulfur$Confluence,
  strontium = strontium$Confluence,
  strontium_88Sr = strontium$Confluence_88Sr,
  strontium_86Sr = strontium$Confluence_86Sr,
  sulfate = sulfate$Confluence,
  thallium = thallium$Confluence,
  thallium_205Tl = thallium$Confluence_205Tl,
  thallium_203Tl = thallium$Confluence_203Tl,
  titanium = titanium$Confluence,
  titanium_49Ti = titanium$Confluence_49Ti,
  titanium_47Ti = titanium$Confluence_47Ti,
  vanadium = vanadium$Confluence,
  yttrium = yttrium$Confluence,
  zinc = zinc$Confluence,
  zinc_68Zn = zinc$Confluence_68Zn,
  zinc_67Zn = zinc$Confluence_67Zn,
  zinc_66Zn = zinc$Confluence_66Zn,
  zirconium = zirconium$Confluence,
  bromide = bromide$Confluence,
  calcium_ion = calcium_ion$Confluence,
  feII = feII$Confluence,
  fluoride = fluoride$Confluence,
  magnesium_ion = magnesium_ion$Confluence,
  potassium_ion = potassium_ion$Confluence,
  sodium_ion = sodium_ion$Confluence
)
```

```{r}
Amous1200 <- data.frame(
  dates = temperature$dates,
  temperature = temperature$Amous,
  ph = ph$Amous,
  eh = eh$Amous,
  o2 = o2$Amous,
  o2_HACH = o2$Amous_hach,
  o2_colorimétrie = o2$Amous_colorimetrie,
  o2_Mettler = o2$Amous_mettler,
  conductivity = conductivity$Amous,
  aluminium = aluminium$Amous,
  antimony = antimony$Amous,
  antimony_123Sb = antimony$Amous_123Sb,
  antimony_121Sb = antimony$Amous_121Sb,
  asV = asV$Amous,
  asIII = asIII$Amous,
  total_arsenic = total_arsenic$Amous,
  baryum = baryum$Amous,
  baryum_138Ba = baryum$Amous_138Ba,
  baryum_137Ba = baryum$Amous_137Ba,
  baryum_136Ba = baryum$Amous_136Ba,
  bore = bore$Amous,
  cadmium = cadmium$Amous,
  cadmium_114Cd = cadmium$Amous_114Cd,
  cadmium_111Cd = cadmium$Amous_111Cd,
  calcium = calcium$Amous,
  calcium_44Ca = calcium$Amous_44Ca,
  calcium_43Ca = calcium$Amous_43Ca,
  caesium = caesium$Amous,
  chromium = chromium$Amous,
  chromium_53Cr = chromium$Amous_53Cr,
  chromium_52Cr = chromium$Amous_52Cr,
  cobalt = cobalt$Amous,
  copper = copper$Amous,
  copper_65Cu = copper$Amous_65Cu,
  copper_63Cu = copper$Amous_63Cu,
  tin = tin$Amous,
  tin_120Sn = tin$Amous_120Sn,
  tin_118Sn = tin$Amous_118Sn,
  total_iron = total_iron$Amous,
  lanthanum = lanthanum$Amous,
  magnesium = magnesium$Amous,
  molybdenum = molybdenum$Amous,
  molybdenum_97Mo = molybdenum$Amous_97Mo,
  molybdenum_95Mo = molybdenum$Amous_95Mo,
  nickel = nickel$Amous,
  nickel_62Ni = nickel$Amous_62Ni,
  nickel_60Ni = nickel$Amous_60Ni,
  nitrate = nitrate$Amous,
  lead = lead$Amous,
  lead_208Pb = lead$Amous_208Pb,
  lead_207Pb = lead$Amous_207Pb,
  lead_206Pb = lead$Amous_206Pb,
  rubidium = rubidium$Amous,
  sodium = sodium$Amous,
  sulfur = sulfur$Amous,
  strontium = strontium$Amous,
  strontium_88Sr = strontium$Amous_88Sr,
  strontium_86Sr = strontium$Amous_86Sr,
  sulfate = sulfate$Amous,
  thallium = thallium$Amous,
  thallium_205Tl = thallium$Amous_205Tl,
  thallium_203Tl = thallium$Amous_203Tl,
  titanium = titanium$Amous,
  titanium_49Ti = titanium$Amous_49Ti,
  titanium_47Ti = titanium$Amous_47Ti,
  vanadium = vanadium$Amous,
  yttrium = yttrium$Amous,
  zinc = zinc$Amous,
  zinc_68Zn = zinc$Amous_68Zn,
  zinc_67Zn = zinc$Amous_67Zn,
  zinc_66Zn = zinc$Amous_66Zn,
  zirconium = zirconium$Amous,
  bromide = bromide$Amous,
  calcium_ion = calcium_ion$Amous,
  feII = feII$Amous,
  fluoride = fluoride$Amous,
  magnesium_ion = magnesium_ion$Amous,
  potassium_ion = potassium_ion$Amous,
  sodium_ion = sodium_ion$Amous
)
```

```{r}
write_delim(Source_S1, here("processed","Source_S1.csv"), delim = ';')
write_delim(S5, here("processed","S5.csv"), delim = ';')
write_delim(COWG, here("processed","COWG.csv"), delim = ';')
write_delim(GAL, here("processed","GAL.csv"), delim = ';')
write_delim(Confluence, here("processed","Confluence.csv"), delim = ';')
write_delim(Amous1200, here("processed","Amous_1200.csv"), delim = ';')
```
