---
title: "COWG recent datas processing"
author: "CLETZ Laura"
date: "11/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(readr)
library(dplyr)
library(tidyverse)
here::i_am("R/tidy_datas.Rmd")
library(here)
```

```{r}
cowg <- read.table(here("raw_data","Carnoules_compas 2019_2021-vérifié-2.csv"), 
                   dec=c(",","."), sep=";", na.strings = c("NA", ""))[-c(1,106:111),]
rownames(cowg) <- 1:nrow(cowg)
```


Cleaning dates format:
```{r}
dates <- cowg[1,3:101]

parse_date_time_robust <- function(x){
   parse_date_time(
     x,
     orders = c('dmy','dmY','mdy','mdY','ymd','y-md'),
     quiet=TRUE
   )
}
dates <- parse_date_time_robust(dates)
```

```{r}
COWG <- data.frame(
  "Dates" = dates,
  "Temperature" = as.numeric(cowg[2,3:101]),
  "pH" = as.numeric(gsub(",", ".", cowg[3,3:101])),
  "Eh" = as.numeric(gsub(",", ".", cowg[4,3:101])),
  "Conductivité" = as.numeric(gsub(",", ".", cowg[5,3:101])),
  "O2" = as.numeric(gsub(",", ".", cowg[10,3:101])),
  "Arséniate" = as.numeric(gsub(",", ".", cowg[23,3:101])),
  "Arsénite" = as.numeric(gsub(",", ".", cowg[24,3:101])),
  "Arsenic_Total" = as.numeric(cowg[25,3:101]),
  "Sodium" = as.numeric(gsub(",", ".", cowg[32,3:101])),
  "Magnésium" = as.numeric(gsub(",", ".", cowg[33,3:101])),
  "Aluminium" = as.numeric(gsub(",", ".", cowg[34,3:101])),
  "Souffre" = as.numeric(gsub(",", ".", cowg[35,3:101])),
  "Calcium" = as.numeric(gsub(",", ".", cowg[37,3:101])),
  "Vanadium" = as.numeric(gsub(",", ".", cowg[40,3:101])),
  "Chrome" = as.numeric(gsub(",", ".", cowg[41,3:101])),
  "Manganèse" = as.numeric(gsub(",", ".", cowg[43,3:101])),
  "Fer" = as.numeric(gsub(",", ".", cowg[44,3:101])),
  "Cobalt" = as.numeric(gsub(",", ".", cowg[45,3:101])),
  "Nickel" = as.numeric(gsub(",", ".", cowg[46,3:101])),
  "Cuivre" = as.numeric(gsub(",", ".", cowg[48,3:101])),
  "Zinc" = as.numeric(gsub(",", ".", cowg[50,3:101])),
  "Rubidium" = as.numeric(gsub(",", ".", cowg[55,3:101])),
  "Strontium" = as.numeric(gsub(",", ".", cowg[57,3:101])),
  "Yttrium" = as.numeric(gsub(",", ".", cowg[58,3:101])),
  "Cadmium" = as.numeric(gsub(",", ".", cowg[62,3:101])),
  "Antimoine" = as.numeric(gsub(",", ".", cowg[66,3:101])),
  "Césium" = as.numeric(gsub(",", ".", cowg[68,3:101])),
  "Baryum" = as.numeric(gsub(",", ".", cowg[70,3:101])),
  "Lanthane" = as.numeric(gsub(",", ".", cowg[72,3:101])),
  "Thallium" = as.numeric(gsub(",", ".", cowg[74,3:101])),
  "Plomb" = as.numeric(gsub(",", ".", cowg[77,3:101])),
  "Uranium" = as.numeric(gsub(",", ".", cowg[78,3:101])),
  "Lithium" = as.numeric(gsub(",", ".", cowg[79,3:101])),
  "Potassium" = as.numeric(gsub(",", ".", cowg[85,3:101])),
  "Silicium" = as.numeric(gsub(",", ".", cowg[89,3:101]))
  )
```

```{r}
write_delim(COWG, here("processed","recent_COWG_daily.csv"), delim = ";")
```

```{r}
monthly_COWG <- COWG %>%
  mutate(
    month = month(as.POSIXlt(Dates, format="%Y-%m-%d")),
    year = year(as.POSIXlt(Dates, format="%Y-%m-%d"))
  ) %>%
  group_by(month, year) %>%
  summarise(Temperature = mean(Temperature),
            pH = mean(Temperature),
            Eh = mean(Eh),
            Conductivité = mean(Conductivité),
            O2 = mean(O2),
            Arséniate = mean(Arséniate),
            Arsénite = mean(Arsénite),
            Arsenic_Total = mean(Arsenic_Total),
            Sodium = mean(Sodium),
            Magnésium = mean(Magnésium),
            Aluminium = mean(Aluminium),
            Souffre = mean(Souffre),
            Calcium = mean(Calcium),
            Vanadium = mean(Vanadium),
            Chrome = mean(Chrome),
            Manganèse = mean(Manganèse),
            Fer = mean(Fer),
            Cobalt = mean(Cobalt),
            Nickel = mean(Nickel),
            Cuivre = mean(Cuivre),
            Zinc = mean(Zinc),
            Rubidium = mean(Rubidium),
            Strontium = mean(Strontium),
            Yttrium = mean(Yttrium),
            Cadmium = mean(Cadmium),
            Antimoine = mean(Antimoine),
            Césium = mean(Césium),
            Baryum = mean(Baryum),
            Lanthane = mean(Lanthane),
            Thallium = mean(Thallium),
            Plomb = mean(Plomb),
            Uranium = mean(Uranium),
            Lithium = mean(Lithium),
            Potassium = mean(Potassium),
            Silicium = mean(Silicium)
            )
```
```{r}
write_delim(monthly_COWG, here("processed","recent_COWG.csv"), delim = ";")
```

