---
title: "Cross-Validation on a small piece of S1 data"
author: "CLETZ Laura"
date: "13/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(data.table)
library(dplyr)
library(tidyverse)
library(lubridate)
library(imputeTS)
library(mgcv)
library(forecast)
library(VIM)
here::i_am("R/CV_S1.Rmd")
library(here)
```

```{r, warning=FALSE}
data <- read.table(here('processed','Source_S1_v2.csv'), dec = c(',','.') , sep = ";", header = TRUE) %>% 
  mutate_at(2:45, function(x) as.numeric(as.character(gsub(',','.', x))))
data$Dates <- as.Date(data$Dates, format="%Y-%m-%d")
```

```{r}
gen <- read.table(here('processed','Generargues_complete.csv'), dec = ',', sep = ";", header = TRUE) 
gen$Dates <- as.Date(gen$Dates, format="%Y-%m-%d")
gen$monthly_rainfall <- as.numeric(gen$monthly_rainfall)

data <- gen %>%
  inner_join(data, by="Dates")
```

```{r}
dis <- read.table(here('processed','S1_discharge.csv'), dec = c(',','.'), sep = ";", header = TRUE)
dis$Dates <- as.Date(dis$Dates, format="%Y-%m-%d")
dis$monthly_discharge <- as.numeric(dis$monthly_discharge)

dis2 <- read.table(here('processed','discharge_ESU.csv'), dec = c(',','.'), sep = ";", header = TRUE)
dis2$Dates <- as.Date(dis2$Dates, format="%Y-%m-%d")

dis3 <- dis %>%
  bind_rows(dis2)

data <- data %>%
  left_join(dis3) %>% 
  distinct(Dates, .keep_all = TRUE)
```

```{r}
test <- data[(1:49),]
test <- test[which(colSums(is.na(test))*100/nrow(test)<=15)]
length(data) ; length(test) ; names(test)
```

# imputeTS imputation

```{r}
data_ts <- test %>%
  mutate_at(2:22, function(x) ts(x, start=c(2004,11), end=c(2008,11), frequency = 12)) %>%
  na_kalman(model = "auto.arima")
```

# GAMMs imputation

## AR(1)

```{r}
data_gamm_ar1 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 1), data = test)
# form = ~ 1 because the observations are already ordered by dates
summary(data_gamm_ar1$gam)
```

## AR(2)

```{r}
data_gamm_ar2 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 2), data = test)
summary(data_gamm_ar2$gam)
```

## AR(3)

```{r}
data_gamm_ar3 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 3), data = test)
summary(data_gamm_ar3$gam)
```

## MA(1)

```{r}
data_gamm_ma1 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, q = 1), data = test)
# form = ~ 1 because the observations are already ordered by dates
summary(data_gamm_ma1$gam)
```

## MA(2)

```{r}
data_gamm_ma2 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, q = 2), data = test)
summary(data_gamm_ma2$gam)
```

## ARMA(1,1)

```{r}
data_gamm_arma11 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 1, q = 1), data = test)
summary(data_gamm_arma11$gam)
```

## ARMA(1,2)

```{r}
#data_gamm_arma12 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
#                      correlation = corARMA(form = ~ 1, p = 1, q = 2), data = test)
#summary(data_gamm_arma12$gam)
```

## ARMA(2,1)

```{r}
data_gamm_arma21 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 2, q = 1), data = test)
summary(data_gamm_arma21$gam)
```

## ARMA(2,2)

```{r}
data_gamm_arma22 <- gamm(Arsenic_Total ~ s(monthly_rainfall) + s(Conductivité), 
                      correlation = corARMA(form = ~ 1, p = 2, q = 2), data = test)
summary(data_gamm_arma22$gam)
```

## Comparison

```{r}
AIC(data_gamm_ar1$lme)
AIC(data_gamm_ar2$lme)
AIC(data_gamm_ar3$lme)
AIC(data_gamm_ma1$lme)
AIC(data_gamm_ma2$lme)
AIC(data_gamm_arma11$lme)
#AIC(data_gamm_arma12$lme)
AIC(data_gamm_arma21$lme)
AIC(data_gamm_arma22$lme)
```
ARMA(1,1) wins.

```{r}
data_gamm <- test
newd <- data.frame(
  monthly_rainfall = data_gamm$monthly_rainfall[which(is.na(data_gamm$Arsenic_Total))],
  Conductivité = data_gamm$Conductivité[which(is.na(data_gamm$Arsenic_Total))]
)
data_gamm$Arsenic_Total[which(is.na(data_gamm$Arsenic_Total))] <- predict.gam(data_gamm_arma11$gam, newd)
```

## Imputation function for GAMMs method

```{r}
impute_GAMMs <- function(df){
  control <- lmeControl(msMaxIter = 200, 
                       msMaxEval = 200,
                       tolerance = 1e-4,
                       niterEM = 50,
                       opt = "optim")
  
  # Check if there is any columns without NAs where we need to impute values
  for( col in (2:ncol(df)) ){ # 2 since the first column is supposed to be Dates
    index_with_na <- which(is.na(df[col]))
    
    if(length(index_with_na) == 0) {
      next
    } 
    
    else {
    newdf <- data.frame( df[[1]][index_with_na] )
    formula <- paste0( names(df[col]), "~")
    
    for( i in (2:ncol(df)) ){
      
       if( names(df[i]) == names(df[col]) ){      
          next
         }
      
      if( sum( is.na( df[[i]][index_with_na] )) > 0 ){
         next
        }
      
      else {
        formula <- paste0( formula, "s(", names(df[i]), ")+" )
        newdf <- cbind(newdf, df[[i]][index_with_na] )
        colnames(newdf)[length(newdf)] <- names(df[i])
          
        if( ncol(newdf) == 6){
          next
        }
      }
    }
    formula <- formula( gsub('.{1}$', '', formula) ) # last '+' removed and conversion to class 'formula'
    
    # Test of different ARMA options
    for(p in (0:1)){
      for(q in (0:p)){
        
        if(p == 0 & q == 0) {
          gamm_best <- gamm(formula, correlation = corARMA(form = ~ 1, p = 1), data = df, control = control)
        }
        
        else {
          gamm_test <- try(gamm(formula, correlation = corARMA(form = ~ 1, p = p, q = q), data = df, control = control), silent = TRUE)

            if (inherits(gamm_test, "try-error")) {
              next
            }
          
          if( AIC(gamm_test$lme) < AIC(gamm_best$lme) ){
            gamm_best <- gamm_test
          }
        }
      }
    }
    
    # Predict the NAs
    df[[col]][index_with_na] <- predict.gam(gamm_best$gam, newdf[-1])
    }
  }
  return(df)
}
```

```{r}
data_gamm <- impute_GAMMs(test)
```

# RMSE

```{r}
fit <- auto.arima(data_ts$Temperature)
val_cal_ts <- KalmanForecast(n.ahead = 210, fit$model)
val_cal_ts <- val_cal_ts$pred[210]
```

```{r}
gam <- gamm(Temperature ~ s(monthly_rainfall) + s(Conductivité) + s(pH) + s(O2), 
                      correlation = corARMA(form = ~ 1, p = 1, q = 1), data = test)
new_data <- data.frame(
  Dates = as.Date("2025-04-01", format = "%Y-%m-%d"),
  Temperature = 16.8,
  monthly_rainfall = 115,2,
  Conductivité = 4560,
  pH = 2.97,
  O2 = 2.86
  )
val_cal_gamm <- predict.gam(gam$gam, newdata = new_data)
```

```{r}
RMSE_ts <- sqrt( (mean( (val_cal_ts - new_data$Temperature)^2 )) )
RMSE_gamm <- sqrt( (mean( (val_cal_gamm - new_data$Temperature)^2 )) )
RMSE_ts ; RMSE_gamm
```

```{r}
data_ts_complete <- read.table(here("processed","S1_ts.csv"), sep = ";", dec = c(",","."), header = TRUE) %>% 
   mutate_at(2:27, function(x) as.numeric(as.character(gsub(',','.', x))))
data$Dates <- as.Date(data$Dates, format="%Y-%m-%d")

fit <- arima(data_ts_complete$Temperature, order=c(1,1,1), seasonal = c(1,1,1))
val_cal_complete <- KalmanForecast(n.ahead = 86, fit$model)
val_cal_complete_pred <- val_cal_complete$pred[86]
RMSE_complete <- sqrt( (mean( (val_cal_complete_pred - new_data$Temperature)^2 )) )
RMSE_complete
```

GAMMs win this time.

# Graphs

```{r}
raw_data <- ts(data$Temperature, start = c(2004,11), end = c(2018,6), frequency = 12)
plot.ts(raw_data, type='l', xlab='Temps', ylab="Température (C°)", lwd = 3,
        xlim = c(2004,2026), xaxt = 'n')
points(ts(data_ts_complete$Temperature, start = c(2004,11), end = c(2018,6), frequency = 12),
       type='l', col = "red")
points(ts(data_ts$Temperature, start = c(2004,11), end = c(2008,11), frequency = 12), 
       type='l', col="blue")
points(ts(data_gamm$Temperature, start = c(2004,11), end = c(2008,11), frequency = 12),
       type='l', col="green")

lissage <- HoltWinters(ts(data_gamm$Temperature, start = c(2004,11), end = c(2008,11), frequency = 12),
                       alpha=0.2, beta=0.2, gamma=0.2, seasonal=c('additive'))
points(lissage$fitted, type='l', col='yellow')

h <- (1:210)
a <- lissage$fitted[37,2]
b <- lissage$fitted[37,3]
s <- lissage$fitted[c(26:37),4]
pred <- a+b*h+s
points(ts(pred, start=c(2008,11), frequency=12), type='l', col='violet')

lissage_ts <- HoltWinters(ts(data_ts_complete$Temperature, start = c(2004,11), end = c(2018,6), frequency = 12),
                       alpha=0.2, beta=0.2, gamma=0.2, seasonal=c('additive'))
h <- (1:86)
a <- lissage_ts$fitted[152,2]
b <- lissage_ts$fitted[152,3]
s <- lissage_ts$fitted[c(141:152),4]
pred_ts <- a+b*h+s
points(ts(pred_ts, start=c(2018,6), frequency=12), type='l', col='darkred')

points(2025.33, new_data$Temperature, col="purple", pch=19)

axis(1, at = seq(2004, 2026, by = 0.5), las = 2)
legend("topleft", c("Série originale", "Série entièrement imputée par imputeTS", "Série partiellement imputée par imputeTS", "Série partiellement imputée par GAMMs", "Lissage à horizon 1", "Lissage à horizon 1:210", " Lissage à horizon 1:86", "Nouveau point"),
       col = c('black','red','blue','green','yellow','violet','darkred','purple'), lty=c(1,1,1,1,1,1,1,NA), pch=c(NA, NA, NA, NA, NA, NA, NA, 19),
       cex=0.4, lwd=c(3,1,1,1,1,1,1))
```
The smoothing on GAMM-imputed data wins.

# K-fold Cross-Validation

```{r}
library(mgcv)
library(caret)

trainGAMM <- function(x, y, correlation = corAR1(form = ~1 | Group), ...){
  require(mgcv)

  formula <- as.formula(paste("y ~", paste(names(x), collapse = " + s("), ")", sep = "s("))

  model <- gamm(formula, data = data.frame(y = y, x), 
                correlation = correlation, ...)

  return(model)
}


predictGAMM <- function(modelFit, newdata, ...){
  
  predictions <- predict(modelFit, newdata = newdata, type = "response", ...)
  
  return(predictions)
}


customGAMM <- list(type = "Regression",
                   library = "mgcv",
                   loop = NULL,
                   parameters = data.frame(parameter = c("method", "optimizer"),
                                           class = c("character", "character"),
                                           label = c("method", "optimizer")),
                   grid = function(x, y, len = NULL) {
                     data.frame(method = "REML",
                                optimizer = "outer",
                                stringsAsFactors = FALSE)
                   },
                   fit = function(x, y, wts, param, lev, last, classProbs, ...){
                     trainGAMM(x, y, method = param$method, optimizer = param$optimizer)
                   },
                   predict = function(modelFit, newdata, submodels = NULL, ...){
                     predictGAMM(modelFit, newdata)
                   },
                   prob = function(modelFit, newdata, submodels = NULL, ...){
                     NULL
                   },
                   sort = function(x) x[order(x[, 1]), ],
                   levels = function(x) x$levels
)


set.seed(9204)
control <- trainControl(method = "cv", number = 5)
#model <- train(Temperature ~ ., data = test,
#               method = customGAMM,
#               trControl = control,
#               na.action = na.omit)
#print(model)
```

```{r}
write_delim(data_gamm, here("processed","S1_gamm.csv"), delim =";")
```



