---
title: "Weather and chemicals correlation analysis"
author: "CLETZ Laura"
date: "12/06/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed:
```{r}
library(dplyr)
library(tidyverse)
here::i_am("R/weather_corr_analysis.Rmd")
library(here)
```


```{r, warning=FALSE}
cowg <- read.table(here('processed','COWG_ts.csv'), dec = c(',','.') , sep = ";", header = TRUE) %>% 
  mutate_at(2:27, function(x) as.numeric(as.character(gsub(',','.', x))))
cowg$Dates <- as.Date(cowg$Dates, format="%Y-%m-%d")
```

```{r}
weather <- read.table(here("processed", "weather.csv"), dec = c(",","."), sep = ";", header = TRUE) %>% 
  mutate_at(2:8, function(x) as.numeric(as.character(gsub(',','.', x))))
weather$Dates <- as.Date(weather$Dates, format="%Y-%m-%d")
```

```{r}
data <- weather %>%
  left_join(cowg, by="Dates")
data[,c(2,9)]
```

The measures for Generargues' rainfall from ADEME and from Meteo-France are similar but there are observations where the gap is too wide.

```{r}
data[,c(6,10)]
```

There might be a link between air temperature and water temperature. It's more visible the days of heatwaves.

```{r, warning = FALSE}
temp_air <- ts(data[,6], start = c(2016,1), end = c(2019,12), frequency = 12)
temp_water <- ts(data[,10], start = c(2016,1), end = c(2019,12), frequency = 12)
fit_air <- decompose(temp_air)
fit_water <- decompose(temp_water)
fit <- data.frame(
  Dates = data$Dates,
  Temp_Air = as.numeric(fit_air$trend),
  Temp_Water = as.numeric(fit_water$trend)
)
ggplot(fit, aes(x = Dates)) +
  geom_line(aes(y = Temp_Air, color = "Température de l'air")) +
  geom_line(aes(y = Temp_Water, color = "Température de l'eau")) +
  theme_minimal() 
```

Apparently not. Inconclusive.

